//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrism.CharMatching.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluePrism.CharMatching.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (searches for an image anywhere within the parent element).
        /// </summary>
        internal static string _0SearchesForAnImageAnywhereWithinTheParentElement {
            get {
                return ResourceManager.GetString("_0SearchesForAnImageAnywhereWithinTheParentElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Column.
        /// </summary>
        internal static string AddColumn {
            get {
                return ResourceManager.GetString("AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding &apos;{0}&apos;.
        /// </summary>
        internal static string Adding0 {
            get {
                return ResourceManager.GetString("Adding0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        internal static string AddRow {
            get {
                return ResourceManager.GetString("AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A font with the name &apos;{0}&apos; already exists. Please choose another.
        /// </summary>
        internal static string AFontWithTheName0AlreadyExistsPleaseChooseAnother {
            get {
                return ResourceManager.GetString("AFontWithTheName0AlreadyExistsPleaseChooseAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A named colour or a six-digit colour string is required.
        /// </summary>
        internal static string ANamedColourOrASixDigitColourStringIsRequired {
            get {
                return ResourceManager.GetString("ANamedColourOrASixDigitColourStringIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to open the Control Panel: {0}.
        /// </summary>
        internal static string AnErrorOccurredTryingToOpenTheControlPanel0 {
            get {
                return ResourceManager.GetString("AnErrorOccurredTryingToOpenTheControlPanel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying changes: 
        ///.
        /// </summary>
        internal static string AnErrorOccurredWhileApplyingChanges {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileApplyingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the font &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        internal static string AnErrorOccurredWhileCreatingTheFont01 {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileCreatingTheFont01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while generating the font: {0}.
        /// </summary>
        internal static string AnErrorOccurredWhileGeneratingTheFont0 {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileGeneratingTheFont0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while importing {0} :
        ///{1}.
        /// </summary>
        internal static string AnErrorOccurredWhileImporting01 {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileImporting01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the image &apos;{0}&apos; : {1}.
        /// </summary>
        internal static string AnErrorOccurredWhileLoadingTheImage01 {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileLoadingTheImage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A region with the name &apos;{0}&apos; already exists in this region editor.
        /// </summary>
        internal static string ARegionWithTheName0AlreadyExistsInThisRegionEditor {
            get {
                return ResourceManager.GetString("ARegionWithTheName0AlreadyExistsInThisRegionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relative parent ({0} above the target region) could not be identified as an image..
        /// </summary>
        internal static string ARelativeParent0AboveTheTargetRegionCouldNotBeIdentifiedAsAnImage {
            get {
                return ResourceManager.GetString("ARelativeParent0AboveTheTargetRegionCouldNotBeIdentifiedAsAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap autotrimtopandbottom {
            get {
                object obj = ResourceManager.GetObject("autotrimtopandbottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Prism font &apos;{0}&apos; generated and saved.
        /// </summary>
        internal static string BluePrismFont0GeneratedAndSaved {
            get {
                return ResourceManager.GetString("BluePrismFont0GeneratedAndSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Prism Fonts (*.bpfont,*.xml)|*.bpfont;*.xml.
        /// </summary>
        internal static string BluePrismFontsBpfontXmlBpfontXml {
            get {
                return ResourceManager.GetString("BluePrismFontsBpfontXmlBpfontXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Prism Fonts (*.xml,*.bpfont)|*.xml;*.bpfont.
        /// </summary>
        internal static string BluePrismFontsXmlBpfontXmlBpfont {
            get {
                return ResourceManager.GetString("BluePrismFontsXmlBpfontXmlBpfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating spacing between &apos;{0}&apos; and &apos;{1}&apos;.
        /// </summary>
        internal static string CalculatingSpacingBetween0And1 {
            get {
                return ResourceManager.GetString("CalculatingSpacingBetween0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close window while work is ongoing.
        /// </summary>
        internal static string CannotCloseWindowWhileWorkIsOngoing {
            get {
                return ResourceManager.GetString("CannotCloseWindowWhileWorkIsOngoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find region identified as an image..
        /// </summary>
        internal static string CannotFindRegionIdentifiedAsAnImage {
            get {
                return ResourceManager.GetString("CannotFindRegionIdentifiedAsAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only test a horizontal or vertical line - not the line from {0} to {1}.
        /// </summary>
        internal static string CanOnlyTestAHorizontalOrVerticalLineNotTheLineFrom0To1 {
            get {
                return ResourceManager.GetString("CanOnlyTestAHorizontalOrVerticalLineNotTheLineFrom0To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string CMCategory_Appearance {
            get {
                return ResourceManager.GetString("CMCategory_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        internal static string CMCategory_Behaviour {
            get {
                return ResourceManager.GetString("CMCategory_Behaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        internal static string CMCategory_Identification {
            get {
                return ResourceManager.GetString("CMCategory_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string CMCategory_Padding {
            get {
                return ResourceManager.GetString("CMCategory_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string CMCategory_Rectangle {
            get {
                return ResourceManager.GetString("CMCategory_Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string CMCategory_Region {
            get {
                return ResourceManager.GetString("CMCategory_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Location.
        /// </summary>
        internal static string CMCategory_RegionLocation {
            get {
                return ResourceManager.GetString("CMCategory_RegionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Rectangle.
        /// </summary>
        internal static string CMCategory_RegionRectangle {
            get {
                return ResourceManager.GetString("CMCategory_RegionRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Padding.
        /// </summary>
        internal static string CMCategory_SearchPadding {
            get {
                return ResourceManager.GetString("CMCategory_SearchPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The x position of the rectangle.
        /// </summary>
        internal static string CMDesciption_TheXPositionOfTheRectangle {
            get {
                return ResourceManager.GetString("CMDesciption_TheXPositionOfTheRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All padding.
        /// </summary>
        internal static string CMDescription_AllPadding {
            get {
                return ResourceManager.GetString("CMDescription_AllPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls where a region&apos;s stored image is searched for within the containing element at run-time. 
        ///
        ///&apos;Fixed&apos; limits the search to the image location originally recorded when modelling the application, plus the additional surrounding area specified in the &apos;Search Padding&apos; property. 
        ///
        ///&apos;Relative&apos; will search for this region relative to where its &apos;&apos;Relative Parent&apos;&apos; is found at run-time. 
        ///
        ///&apos;Anywhere&apos; will search the entirety of the region&apos;s parent element, and is only available when the &apos;&apos;Location Method&apos;&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CMDescription_ControlsWhereARegionSStoredImageIsSearchedForWithinTheContainingElementAtRunTim {
            get {
                return ResourceManager.GetString("CMDescription_ControlsWhereARegionSStoredImageIsSearchedForWithinTheContainingEle" +
                        "mentAtRunTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externally registered chars associated with the region.
        /// </summary>
        internal static string CMDescription_ExternallyRegisteredCharsAssociatedWithTheRegion {
            get {
                return ResourceManager.GetString("CMDescription_ExternallyRegisteredCharsAssociatedWithTheRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method used to locate a region within the containing element at run-time.
        ///
        ///&apos;Image&apos; will locate the region by searching for the region&apos;s stored image at run-time;
        ///Intended for form elements with static content such as labels, icons and buttons.
        ///
        ///&apos;Coordinates&apos; will locate the region by using the fixed rectangle that defines the region;
        ///Intended for elements that contain dynamic content�such as text, checkboxes and combo-boxes..
        /// </summary>
        internal static string CMDescription_MethodUsedToLocateARegionWithinTheContainingElementAtRunTimeImageWillLocateTheR {
            get {
                return ResourceManager.GetString("CMDescription_MethodUsedToLocateARegionWithinTheContainingElementAtRunTimeImageWi" +
                        "llLocateTheR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows or hides the region within the region editor. If invisible, a region can still be selected using the drop down menu.
        /// </summary>
        internal static string CMDescription_ShowsOrHidesTheRegionWithinTheRegionEditorIfInvisibleARegionCanStillBeSelectedU {
            get {
                return ResourceManager.GetString("CMDescription_ShowsOrHidesTheRegionWithinTheRegionEditorIfInvisibleARegionCanStil" +
                        "lBeSelectedU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the area around an image&apos;s original location that the region&apos;s stored image will be searched for at run-time..
        /// </summary>
        internal static string CMDescription_SpecifiesTheAreaAroundAnImageSOriginalLocationThatTheRegionSStoredImageWillBeSe {
            get {
                return ResourceManager.GetString("CMDescription_SpecifiesTheAreaAroundAnImageSOriginalLocationThatTheRegionSStoredI" +
                        "mageWillBeSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the tolerance when comparing the R, G and B components of an image&apos;s pixels at run-time. Valid values are 0 through 255.
        /// </summary>
        internal static string CMDescription_SpecifiesTheToleranceWhenComparingTheRGAndBComponentsOfAnImageSPixelsAtRunTimeV {
            get {
                return ResourceManager.GetString("CMDescription_SpecifiesTheToleranceWhenComparingTheRGAndBComponentsOfAnImageSPixe" +
                        "lsAtRunTimeV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Blue Prism font that is used in this region.
        /// </summary>
        internal static string CMDescription_TheBluePrismFontThatIsUsedInThisRegion {
            get {
                return ResourceManager.GetString("CMDescription_TheBluePrismFontThatIsUsedInThisRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bottom of the padding.
        /// </summary>
        internal static string CMDescription_TheBottomOfThePadding {
            get {
                return ResourceManager.GetString("CMDescription_TheBottomOfThePadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The direction in which the list goes.
        /// </summary>
        internal static string CMDescription_TheDirectionInWhichTheListGoes {
            get {
                return ResourceManager.GetString("CMDescription_TheDirectionInWhichTheListGoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height of the rectangle.
        /// </summary>
        internal static string CMDescription_TheHeightOfTheRectangle {
            get {
                return ResourceManager.GetString("CMDescription_TheHeightOfTheRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left of the padding.
        /// </summary>
        internal static string CMDescription_TheLeftOfThePadding {
            get {
                return ResourceManager.GetString("CMDescription_TheLeftOfThePadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location in the control that region goes to.
        /// </summary>
        internal static string CMDescription_TheLocationInTheControlThatRegionGoesTo {
            get {
                return ResourceManager.GetString("CMDescription_TheLocationInTheControlThatRegionGoesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location in the control that region starts from.
        /// </summary>
        internal static string CMDescription_TheLocationInTheControlThatRegionStartsFrom {
            get {
                return ResourceManager.GetString("CMDescription_TheLocationInTheControlThatRegionStartsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of this region.
        /// </summary>
        internal static string CMDescription_TheNameOfThisRegion {
            get {
                return ResourceManager.GetString("CMDescription_TheNameOfThisRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of pixels between each element in the list.
        /// </summary>
        internal static string CMDescription_TheNumberOfPixelsBetweenEachElementInTheList {
            get {
                return ResourceManager.GetString("CMDescription_TheNumberOfPixelsBetweenEachElementInTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rectangle which defines this region.
        /// </summary>
        internal static string CMDescription_TheRectangleWhichDefinesThisRegion {
            get {
                return ResourceManager.GetString("CMDescription_TheRectangleWhichDefinesThisRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The region from which this region&apos;s location is relatively calculated from at run-time..
        /// </summary>
        internal static string CMDescription_TheRegionFromWhichThisRegionSLocationIsRelativelyCalculatedFromAtRunTime {
            get {
                return ResourceManager.GetString("CMDescription_TheRegionFromWhichThisRegionSLocationIsRelativelyCalculatedFromAtRu" +
                        "nTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right of the padding.
        /// </summary>
        internal static string CMDescription_TheRightOfThePadding {
            get {
                return ResourceManager.GetString("CMDescription_TheRightOfThePadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The top of the padding.
        /// </summary>
        internal static string CMDescription_TheTopOfThePadding {
            get {
                return ResourceManager.GetString("CMDescription_TheTopOfThePadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the rectangle.
        /// </summary>
        internal static string CMDescription_TheWidthOfTheRectangle {
            get {
                return ResourceManager.GetString("CMDescription_TheWidthOfTheRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The y position of the rectangle.
        /// </summary>
        internal static string CMDescription_TheYPositionOfTheRectangle {
            get {
                return ResourceManager.GetString("CMDescription_TheYPositionOfTheRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to retain the image from the spied region in this region.
        /// </summary>
        internal static string CMDescription_TrueToRetainTheImageFromTheSpiedRegionInThisRegion {
            get {
                return ResourceManager.GetString("CMDescription_TrueToRetainTheImageFromTheSpiedRegionInThisRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to use grayscale in the image to search for this region.
        /// </summary>
        internal static string CMDescription_TrueToUseGrayscaleInTheImageToSearchForThisRegion {
            get {
                return ResourceManager.GetString("CMDescription_TrueToUseGrayscaleInTheImageToSearchForThisRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined data associated with the object.
        /// </summary>
        internal static string CMDescription_UserDefinedDataAssociatedWithTheObject {
            get {
                return ResourceManager.GetString("CMDescription_UserDefinedDataAssociatedWithTheObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string CMDisplayName_Active {
            get {
                return ResourceManager.GetString("CMDisplayName_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string CMDisplayName_All {
            get {
                return ResourceManager.GetString("CMDisplayName_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BorderColor.
        /// </summary>
        internal static string CMDisplayName_BorderColor {
            get {
                return ResourceManager.GetString("CMDisplayName_BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string CMDisplayName_Bottom {
            get {
                return ResourceManager.GetString("CMDisplayName_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chars.
        /// </summary>
        internal static string CMDisplayName_Chars {
            get {
                return ResourceManager.GetString("CMDisplayName_Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour Tolerance.
        /// </summary>
        internal static string CMDisplayName_ColourTolerance {
            get {
                return ResourceManager.GetString("CMDisplayName_ColourTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string CMDisplayName_Container {
            get {
                return ResourceManager.GetString("CMDisplayName_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayedImage.
        /// </summary>
        internal static string CMDisplayName_DisplayedImage {
            get {
                return ResourceManager.GetString("CMDisplayName_DisplayedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feathered.
        /// </summary>
        internal static string CMDisplayName_Feathered {
            get {
                return ResourceManager.GetString("CMDisplayName_Feathered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillColor.
        /// </summary>
        internal static string CMDisplayName_FillColor {
            get {
                return ResourceManager.GetString("CMDisplayName_FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string CMDisplayName_Font {
            get {
                return ResourceManager.GetString("CMDisplayName_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string CMDisplayName_From {
            get {
                return ResourceManager.GetString("CMDisplayName_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale.
        /// </summary>
        internal static string CMDisplayName_Greyscale {
            get {
                return ResourceManager.GetString("CMDisplayName_Greyscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuideDistance.
        /// </summary>
        internal static string CMDisplayName_GuideDistance {
            get {
                return ResourceManager.GetString("CMDisplayName_GuideDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string CMDisplayName_Height {
            get {
                return ResourceManager.GetString("CMDisplayName_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hovering.
        /// </summary>
        internal static string CMDisplayName_Hovering {
            get {
                return ResourceManager.GetString("CMDisplayName_Hovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string CMDisplayName_Id {
            get {
                return ResourceManager.GetString("CMDisplayName_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string CMDisplayName_Image {
            get {
                return ResourceManager.GetString("CMDisplayName_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerRectangle.
        /// </summary>
        internal static string CMDisplayName_InnerRectangle {
            get {
                return ResourceManager.GetString("CMDisplayName_InnerRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAcceptingMouseInput.
        /// </summary>
        internal static string CMDisplayName_IsAcceptingMouseInput {
            get {
                return ResourceManager.GetString("CMDisplayName_IsAcceptingMouseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsWithinContainerImage.
        /// </summary>
        internal static string CMDisplayName_IsWithinContainerImage {
            get {
                return ResourceManager.GetString("CMDisplayName_IsWithinContainerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string CMDisplayName_Label {
            get {
                return ResourceManager.GetString("CMDisplayName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string CMDisplayName_Left {
            get {
                return ResourceManager.GetString("CMDisplayName_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDirection.
        /// </summary>
        internal static string CMDisplayName_ListDirection {
            get {
                return ResourceManager.GetString("CMDisplayName_ListDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Method.
        /// </summary>
        internal static string CMDisplayName_LocationMethod {
            get {
                return ResourceManager.GetString("CMDisplayName_LocationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string CMDisplayName_Mode {
            get {
                return ResourceManager.GetString("CMDisplayName_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CMDisplayName_Name {
            get {
                return ResourceManager.GetString("CMDisplayName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string CMDisplayName_Padding {
            get {
                return ResourceManager.GetString("CMDisplayName_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaddingRectangle.
        /// </summary>
        internal static string CMDisplayName_PaddingRectangle {
            get {
                return ResourceManager.GetString("CMDisplayName_PaddingRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string CMDisplayName_Position {
            get {
                return ResourceManager.GetString("CMDisplayName_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string CMDisplayName_Rectangle {
            get {
                return ResourceManager.GetString("CMDisplayName_Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Parent.
        /// </summary>
        internal static string CMDisplayName_RelativeParent {
            get {
                return ResourceManager.GetString("CMDisplayName_RelativeParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelativeRegionLines.
        /// </summary>
        internal static string CMDisplayName_RelativeRegionLines {
            get {
                return ResourceManager.GetString("CMDisplayName_RelativeRegionLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain Image.
        /// </summary>
        internal static string CMDisplayName_RetainImage {
            get {
                return ResourceManager.GetString("CMDisplayName_RetainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string CMDisplayName_Right {
            get {
                return ResourceManager.GetString("CMDisplayName_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Padding.
        /// </summary>
        internal static string CMDisplayName_SearchPadding {
            get {
                return ResourceManager.GetString("CMDisplayName_SearchPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string CMDisplayName_Selected {
            get {
                return ResourceManager.GetString("CMDisplayName_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowPadding.
        /// </summary>
        internal static string CMDisplayName_ShowPadding {
            get {
                return ResourceManager.GetString("CMDisplayName_ShowPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string CMDisplayName_Tag {
            get {
                return ResourceManager.GetString("CMDisplayName_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string CMDisplayName_To {
            get {
                return ResourceManager.GetString("CMDisplayName_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string CMDisplayName_Top {
            get {
                return ResourceManager.GetString("CMDisplayName_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string CMDisplayName_Visible {
            get {
                return ResourceManager.GetString("CMDisplayName_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string CMDisplayName_Width {
            get {
                return ResourceManager.GetString("CMDisplayName_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        internal static string CMEnum_Coordinates {
            get {
                return ResourceManager.GetString("CMEnum_Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string CMEnum_Image {
            get {
                return ResourceManager.GetString("CMEnum_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column: {0} not within grid of width: {1}.
        /// </summary>
        internal static string Column0NotWithinGridOfWidth1 {
            get {
                return ResourceManager.GetString("Column0NotWithinGridOfWidth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_16x16 {
            get {
                object obj = ResourceManager.GetObject("copy_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find property {0}.
        /// </summary>
        internal static string CouldNotFindProperty0 {
            get {
                return ResourceManager.GetString("CouldNotFindProperty0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cut_16x16 {
            get {
                object obj = ResourceManager.GetObject("cut_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data must be provided for a font.
        /// </summary>
        internal static string DataMustBeProvidedForAFont {
            get {
                return ResourceManager.GetString("DataMustBeProvidedForAFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_16x16 {
            get {
                object obj = ResourceManager.GetObject("delete_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Font?.
        /// </summary>
        internal static string DeleteFont {
            get {
                return ResourceManager.GetString("DeleteFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Last Column.
        /// </summary>
        internal static string DeleteLastColumn {
            get {
                return ResourceManager.GetString("DeleteLastColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Last Row.
        /// </summary>
        internal static string DeleteLastRow {
            get {
                return ResourceManager.GetString("DeleteLastRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the font &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteTheFont0 {
            get {
                return ResourceManager.GetString("DeleteTheFont0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not support IComparable.
        /// </summary>
        internal static string DoesNotSupportIComparable {
            get {
                return ResourceManager.GetString("DoesNotSupportIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_16x16 {
            get {
                object obj = ResourceManager.GetObject("edit_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Rows and Columns.
        /// </summary>
        internal static string EditRowsAndColumns {
            get {
                return ResourceManager.GetString("EditRowsAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty fonts detected.
        /// </summary>
        internal static string EmptyFontsDetected {
            get {
                return ResourceManager.GetString("EmptyFontsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endRow({0}) must be between 0 and {1}.
        /// </summary>
        internal static string EndRow0MustBeBetween0And1 {
            get {
                return ResourceManager.GetString("EndRow0MustBeBetween0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endRow ({1}) must not exceed startRow ({0}).
        /// </summary>
        internal static string EndRow1MustNotExceedStartRow0 {
            get {
                return ResourceManager.GetString("EndRow1MustNotExceedStartRow0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EraseBlocks parameter cannot be used unless identifying by background colour.
        /// </summary>
        internal static string EraseBlocksParameterCannotBeUsedUnlessIdentifyingByBackgroundColour {
            get {
                return ResourceManager.GetString("EraseBlocksParameterCannotBeUsedUnlessIdentifyingByBackgroundColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred : {0}.
        /// </summary>
        internal static string ErrorOccurred0 {
            get {
                return ResourceManager.GetString("ErrorOccurred0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - too many loop iterations in function RemoveEnclosingBlocksFromPixRect.
        /// </summary>
        internal static string ErrorTooManyLoopIterationsInFunctionRemoveEnclosingBlocksFromPixRect {
            get {
                return ResourceManager.GetString("ErrorTooManyLoopIterationsInFunctionRemoveEnclosingBlocksFromPixRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exportfile_16x16 {
            get {
                object obj = ResourceManager.GetObject("exportfile_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exportfile_16x161 {
            get {
                object obj = ResourceManager.GetObject("exportfile_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Font....
        /// </summary>
        internal static string ExtractingFont {
            get {
                return ResourceManager.GetString("ExtractingFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find top of left character in {0}{1}.
        /// </summary>
        internal static string FailedToFindTopOfLeftCharacterIn01 {
            get {
                return ResourceManager.GetString("FailedToFindTopOfLeftCharacterIn01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_16x16 {
            get {
                object obj = ResourceManager.GetObject("file_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_16x16 {
            get {
                object obj = ResourceManager.GetObject("font_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Editor.
        /// </summary>
        internal static string FontEditor {
            get {
                return ResourceManager.GetString("FontEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font generation aborted.
        /// </summary>
        internal static string FontGenerationAborted {
            get {
                return ResourceManager.GetString("FontGenerationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Name.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts cannot be properly generated because font smoothing is currently enabled on this system. The feature must be disabled before proceeding.
        ///
        ///It can be disabled by unticking &apos;Smooth edges of screen fonts&apos; in Control Panel -&gt; System -&gt; Advanced -&gt; Performance Settings -&gt; Visual Effects.
        ///
        ///Do you want to open the System Control Panel now?.
        /// </summary>
        internal static string FontsCannotBeProperlyGeneratedBecauseFontSmoothingIsCurrentlyEnabledOnThisSyste {
            get {
                return ResourceManager.GetString("FontsCannotBeProperlyGeneratedBecauseFontSmoothingIsCurrentlyEnabledOnThisSyste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Smoothing Enabled.
        /// </summary>
        internal static string FontSmoothingEnabled {
            get {
                return ResourceManager.GetString("FontSmoothingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a Blue Prism Font.
        /// </summary>
        internal static string GenerateABluePrismFont {
            get {
                return ResourceManager.GetString("GenerateABluePrismFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a Blue Prism OCR Plus font.
        /// </summary>
        internal static string GenerateABluePrismOCRPlusFont {
            get {
                return ResourceManager.GetString("GenerateABluePrismOCRPlusFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Blue Prism font: {0}.
        /// </summary>
        internal static string GeneratedBluePrismFont0 {
            get {
                return ResourceManager.GetString("GeneratedBluePrismFont0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Region {0}.
        /// </summary>
        internal static string GridRegion0 {
            get {
                return ResourceManager.GetString("GridRegion0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Characters.
        /// </summary>
        internal static string HideCharacters {
            get {
                return ResourceManager.GetString("HideCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Region Editor.
        /// </summary>
        internal static string HideRegionEditor {
            get {
                return ResourceManager.GetString("HideRegionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images (*.bmp, *.png, *.jpg, *.gif)|*.bmp;*.png;*.jpg;*.gif|All Files (*.*)|*.*.
        /// </summary>
        internal static string ImagesBmpPngJpgGifBmpPngJpgGifAllFiles {
            get {
                return ResourceManager.GetString("ImagesBmpPngJpgGifBmpPngJpgGifAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid direction specified: .
        /// </summary>
        internal static string InvalidDirectionSpecified {
            get {
                return ResourceManager.GetString("InvalidDirectionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encoded mask value: .
        /// </summary>
        internal static string InvalidEncodedMaskValue {
            get {
                return ResourceManager.GetString("InvalidEncodedMaskValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format - expected even number of letter pairs.
        /// </summary>
        internal static string InvalidFileFormatExpectedEvenNumberOfLetterPairs {
            get {
                return ResourceManager.GetString("InvalidFileFormatExpectedEvenNumberOfLetterPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid font name.
        /// </summary>
        internal static string InvalidFontName {
            get {
                return ResourceManager.GetString("InvalidFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid kernvalue for &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidKernvalueFor0 {
            get {
                return ResourceManager.GetString("InvalidKernvalueFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid kernvalue for {0}: {1}.
        /// </summary>
        internal static string InvalidKernvalueFor01 {
            get {
                return ResourceManager.GetString("InvalidKernvalueFor01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid letter for &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidLetterFor0 {
            get {
                return ResourceManager.GetString("InvalidLetterFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value attribute for {0}: {1}.
        /// </summary>
        internal static string InvalidValueAttributeFor01 {
            get {
                return ResourceManager.GetString("InvalidValueAttributeFor01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidValueFor0 {
            get {
                return ResourceManager.GetString("InvalidValueFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for {0}: {1}.
        /// </summary>
        internal static string InvalidValueFor01 {
            get {
                return ResourceManager.GetString("InvalidValueFor01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Region {0}.
        /// </summary>
        internal static string ListRegion0 {
            get {
                return ResourceManager.GetString("ListRegion0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Error.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mag_16x16 {
            get {
                object obj = ResourceManager.GetObject("mag_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masks must be the same size to check for containment.
        /// </summary>
        internal static string MasksMustBeTheSameSizeToCheckForContainment {
            get {
                return ResourceManager.GetString("MasksMustBeTheSameSizeToCheckForContainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;min&apos; and &apos;max&apos; must be the same type - ({0}, {1}).
        /// </summary>
        internal static string MinAndMaxMustBeTheSameType01 {
            get {
                return ResourceManager.GetString("MinAndMaxMustBeTheSameType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;min&apos; cannot be greater than &apos;max&apos;.
        /// </summary>
        internal static string MinCannotBeGreaterThanMax {
            get {
                return ResourceManager.GetString("MinCannotBeGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch between size and number of bits: .
        /// </summary>
        internal static string MismatchBetweenSizeAndNumberOfBits {
            get {
                return ResourceManager.GetString("MismatchBetweenSizeAndNumberOfBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already in use.
        /// </summary>
        internal static string NameAlreadyInUse {
            get {
                return ResourceManager.GetString("NameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        internal static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_16x16 {
            get {
                object obj = ResourceManager.GetObject("new_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Font {0}.
        /// </summary>
        internal static string NewFont0 {
            get {
                return ResourceManager.GetString("NewFont0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CharUnion set, cannot merge characters.
        /// </summary>
        internal static string NoCharUnionSetCannotMergeCharacters {
            get {
                return ResourceManager.GetString("NoCharUnionSetCannotMergeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No font selected.
        /// </summary>
        internal static string NoFontSelected {
            get {
                return ResourceManager.GetString("NoFontSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No font set in union - cannot merge characters.
        /// </summary>
        internal static string NoFontSetInUnionCannotMergeCharacters {
            get {
                return ResourceManager.GetString("NoFontSetInUnionCannotMergeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No font with the name &apos;{0}&apos; was found.
        /// </summary>
        internal static string NoFontWithTheName0WasFound {
            get {
                return ResourceManager.GetString("NoFontWithTheName0WasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;None&gt;.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operation.
        /// </summary>
        internal static string NoOperation {
            get {
                return ResourceManager.GetString("NoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Region Selected&gt;.
        /// </summary>
        internal static string NoRegionSelected {
            get {
                return ResourceManager.GetString("NoRegionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid font definition; Found root node: {0}.
        /// </summary>
        internal static string NotAValidFontDefinitionFoundRootNode0 {
            get {
                return ResourceManager.GetString("NotAValidFontDefinitionFoundRootNode0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome not recognised.
        /// </summary>
        internal static string OutcomeNotRecognised {
            get {
                return ResourceManager.GetString("OutcomeNotRecognised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap padbottom {
            get {
                object obj = ResourceManager.GetObject("padbottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad Bottom.
        /// </summary>
        internal static string PadBottom_helpText {
            get {
                return ResourceManager.GetString("PadBottom_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap padleft {
            get {
                object obj = ResourceManager.GetObject("padleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad Left.
        /// </summary>
        internal static string PadLeft_helpText {
            get {
                return ResourceManager.GetString("PadLeft_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap padright {
            get {
                object obj = ResourceManager.GetObject("padright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad Right.
        /// </summary>
        internal static string PadRight_helpText {
            get {
                return ResourceManager.GetString("PadRight_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap padtop {
            get {
                object obj = ResourceManager.GetObject("padtop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad Top.
        /// </summary>
        internal static string PadTop_helpText {
            get {
                return ResourceManager.GetString("PadTop_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap palette_16x16 {
            get {
                object obj = ResourceManager.GetObject("palette_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste_16x16 {
            get {
                object obj = ResourceManager.GetObject("paste_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the Blue Prism Font to be generated from the system font: {0}.
        /// </summary>
        internal static string PleaseEnterANameForTheBluePrismFontToBeGeneratedFromTheSystemFont0 {
            get {
                return ResourceManager.GetString("PleaseEnterANameForTheBluePrismFontToBeGeneratedFromTheSystemFont0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the font.
        /// </summary>
        internal static string PleaseEnterANameForTheFont {
            get {
                return ResourceManager.GetString("PleaseEnterANameForTheFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid font.
        /// </summary>
        internal static string PleaseSelectAValidFont {
            get {
                return ResourceManager.GetString("PleaseSelectAValidFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The defined regions refer to {COUNT, plural, one {1 font} other {# fonts}} with no defined characters: {FONTLIST}.
        ///
        ///The character matching operations using {COUNT, plural, one {this font} other {these fonts}} will fail until {COUNT, plural, one {it is} other {they are}} populated, either by importing the {COUNT, plural, one {font} other {fonts}} or generating {COUNT, plural, one {it} other {them}} in this environment.
        ///
        ///Save changes and continue anyway?.
        /// </summary>
        internal static string plural_WarningTheDefinedRegionsReferToCOUNTPluralOne1FontOtherFontsWith {
            get {
                return ResourceManager.GetString("plural_WarningTheDefinedRegionsReferToCOUNTPluralOne1FontOtherFontsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point &apos;{0}&apos; is not within grid bounds: {1}.
        /// </summary>
        internal static string Point0IsNotWithinGridBounds1 {
            get {
                return ResourceManager.GetString("Point0IsNotWithinGridBounds1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pointer_16x16 {
            get {
                object obj = ResourceManager.GetObject("pointer_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle: {0} is out of bounds for the given image - size: {1}.
        /// </summary>
        internal static string Rectangle0IsOutOfBoundsForTheGivenImageSize1 {
            get {
                return ResourceManager.GetString("Rectangle0IsOutOfBoundsForTheGivenImageSize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangles must be same size: {0} != {1}.
        /// </summary>
        internal static string RectanglesMustBeSameSize01 {
            get {
                return ResourceManager.GetString("RectanglesMustBeSameSize01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region {0}.
        /// </summary>
        internal static string Region0 {
            get {
                return ResourceManager.GetString("Region0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap regiongrid_16x16 {
            get {
                object obj = ResourceManager.GetObject("regiongrid_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap regionlist_16x16 {
            get {
                object obj = ResourceManager.GetObject("regionlist_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anywhere.
        /// </summary>
        internal static string RegionPosition_Anywhere {
            get {
                return ResourceManager.GetString("RegionPosition_Anywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string RegionPosition_Fixed {
            get {
                return ResourceManager.GetString("RegionPosition_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        internal static string RegionPosition_Relative {
            get {
                return ResourceManager.GetString("RegionPosition_Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap regionvanilla_16x16 {
            get {
                object obj = ResourceManager.GetObject("regionvanilla_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row: {0} not within grid of height: {1}.
        /// </summary>
        internal static string Row0NotWithinGridOfHeight1 {
            get {
                return ResourceManager.GetString("Row0NotWithinGridOfHeight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Blue Prism font: {0}.
        /// </summary>
        internal static string SavingBluePrismFont0 {
            get {
                return ResourceManager.GetString("SavingBluePrismFont0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (searches for an image at a fixed position).
        /// </summary>
        internal static string SearchesForAnImageAtAFixedPosition {
            get {
                return ResourceManager.GetString("SearchesForAnImageAtAFixedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (searches for an image at a fixed position including search padding).
        /// </summary>
        internal static string SearchesForAnImageAtAFixedPositionIncludingSearchPadding {
            get {
                return ResourceManager.GetString("SearchesForAnImageAtAFixedPositionIncludingSearchPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (searches for an image at a position relative to {0}).
        /// </summary>
        internal static string SearchesForAnImageAtAPositionRelativeTo0 {
            get {
                return ResourceManager.GetString("SearchesForAnImageAtAPositionRelativeTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (searches for an image at a position relative to {0} including search padding).
        /// </summary>
        internal static string SearchesForAnImageAtAPositionRelativeTo0IncludingSearchPadding {
            get {
                return ResourceManager.GetString("SearchesForAnImageAtAPositionRelativeTo0IncludingSearchPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (searches for the region using coordinates at a fixed position).
        /// </summary>
        internal static string SearchesForTheRegionUsingCoordinatesAtAFixedPosition {
            get {
                return ResourceManager.GetString("SearchesForTheRegionUsingCoordinatesAtAFixedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (searches for the region using coordinates at a fixed position including search padding).
        /// </summary>
        internal static string SearchesForTheRegionUsingCoordinatesAtAFixedPositionIncludingSearchPadding {
            get {
                return ResourceManager.GetString("SearchesForTheRegionUsingCoordinatesAtAFixedPositionIncludingSearchPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (searches for the region using coordinates at a position relative to {0}).
        /// </summary>
        internal static string SearchesForTheRegionUsingCoordinatesAtAPositionRelativeTo0 {
            get {
                return ResourceManager.GetString("SearchesForTheRegionUsingCoordinatesAtAPositionRelativeTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (searches for the region using coordinates at a position relative to {0} including search padding).
        /// </summary>
        internal static string SearchesForTheRegionUsingCoordinatesAtAPositionRelativeTo0IncludingSearchPadding {
            get {
                return ResourceManager.GetString("SearchesForTheRegionUsingCoordinatesAtAPositionRelativeTo0IncludingSearchPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shiftdown {
            get {
                object obj = ResourceManager.GetObject("shiftdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Down.
        /// </summary>
        internal static string ShiftDown_helpText {
            get {
                return ResourceManager.GetString("ShiftDown_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shiftleft {
            get {
                object obj = ResourceManager.GetObject("shiftleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Left.
        /// </summary>
        internal static string ShiftLeft_helpText {
            get {
                return ResourceManager.GetString("ShiftLeft_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shiftright {
            get {
                object obj = ResourceManager.GetObject("shiftright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Right.
        /// </summary>
        internal static string ShiftRight_helpText {
            get {
                return ResourceManager.GetString("ShiftRight_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shiftup {
            get {
                object obj = ResourceManager.GetObject("shiftup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Up.
        /// </summary>
        internal static string ShiftUp_helpText {
            get {
                return ResourceManager.GetString("ShiftUp_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Characters.
        /// </summary>
        internal static string ShowCharacters {
            get {
                return ResourceManager.GetString("ShowCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Region Editor.
        /// </summary>
        internal static string ShowRegionEditor {
            get {
                return ResourceManager.GetString("ShowRegionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the state mask must match the size of this character&apos;s glyph.
        /// </summary>
        internal static string SizeOfTheStateMaskMustMatchTheSizeOfThisCharacterSGlyph {
            get {
                return ResourceManager.GetString("SizeOfTheStateMaskMustMatchTheSizeOfThisCharacterSGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startRow ({0}) must be between 0 and {1}.
        /// </summary>
        internal static string StartRow0MustBeBetween0And1 {
            get {
                return ResourceManager.GetString("StartRow0MustBeBetween0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing {0} ({1}).
        /// </summary>
        internal static string Testing01 {
            get {
                return ResourceManager.GetString("Testing01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font &apos;{0}&apos; contains no characters.
        /// </summary>
        internal static string TheFont0ContainsNoCharacters {
            get {
                return ResourceManager.GetString("TheFont0ContainsNoCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font &apos;{0}&apos; does not exist. Refreshing fonts list....
        /// </summary>
        internal static string TheFont0DoesNotExistRefreshingFontsList {
            get {
                return ResourceManager.GetString("TheFont0DoesNotExistRefreshingFontsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font &apos;{0}&apos; was not recognised..
        /// </summary>
        internal static string TheFont0WasNotRecognised {
            get {
                return ResourceManager.GetString("TheFont0WasNotRecognised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font name cannot be empty.
        /// </summary>
        internal static string TheFontNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("TheFontNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fonts in this store cannot be modified.
        /// </summary>
        internal static string TheFontsInThisStoreCannotBeModified {
            get {
                return ResourceManager.GetString("TheFontsInThisStoreCannotBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given XML file could not be parsed into a font. Root element found: {0}.
        /// </summary>
        internal static string TheGivenXMLFileCouldNotBeParsedIntoAFontRootElementFound0 {
            get {
                return ResourceManager.GetString("TheGivenXMLFileCouldNotBeParsedIntoAFontRootElementFound0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string TheMethodOrOperationIsNotImplemented {
            get {
                return ResourceManager.GetString("TheMethodOrOperationIsNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is already in use. Please choose another.
        /// </summary>
        internal static string TheName0IsAlreadyInUsePleaseChooseAnother {
            get {
                return ResourceManager.GetString("TheName0IsAlreadyInUsePleaseChooseAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property could not be reset: {0}.
        /// </summary>
        internal static string ThePropertyCouldNotBeReset0 {
            get {
                return ResourceManager.GetString("ThePropertyCouldNotBeReset0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mask cannot be stripped from the {0} any further.
        /// </summary>
        internal static string ThisMaskCannotBeStrippedFromThe0AnyFurther {
            get {
                return ResourceManager.GetString("ThisMaskCannotBeStrippedFromThe0AnyFurther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will overwrite an existing font. Is that correct?.
        /// </summary>
        internal static string ThisWillOverwriteAnExistingFontIsThatCorrect {
            get {
                return ResourceManager.GetString("ThisWillOverwriteAnExistingFontIsThatCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trimbottom {
            get {
                object obj = ResourceManager.GetObject("trimbottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Bottom.
        /// </summary>
        internal static string TrimBottom_helpText {
            get {
                return ResourceManager.GetString("TrimBottom_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trimleft {
            get {
                object obj = ResourceManager.GetObject("trimleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Left.
        /// </summary>
        internal static string TrimLeft_helpText {
            get {
                return ResourceManager.GetString("TrimLeft_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trimright {
            get {
                object obj = ResourceManager.GetObject("trimright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Right.
        /// </summary>
        internal static string TrimRight_helpText {
            get {
                return ResourceManager.GetString("TrimRight_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trimtop {
            get {
                object obj = ResourceManager.GetObject("trimtop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Top.
        /// </summary>
        internal static string TrimTop_helpText {
            get {
                return ResourceManager.GetString("TrimTop_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import file {0}, a font named {1} already exists.
        /// </summary>
        internal static string UnableToImportFile0AFontNamed1AlreadyExists {
            get {
                return ResourceManager.GetString("UnableToImportFile0AFontNamed1AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xmlfile_16x16 {
            get {
                object obj = ResourceManager.GetObject("xmlfile_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;x&apos; must be a PropertyDescriptor.
        /// </summary>
        internal static string XMustBeAPropertyDescriptor {
            get {
                return ResourceManager.GetString("XMustBeAPropertyDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;y&apos; must be a PropertyDescriptor.
        /// </summary>
        internal static string YMustBeAPropertyDescriptor {
            get {
                return ResourceManager.GetString("YMustBeAPropertyDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can search automatically for fonts which match the selected region.
        ///
        ///Select a region and enter the text value held in it. A region containing less characters is actually more reliable and likely to yield a more accurate result
        ///
        ///You can modify the parameters which determine the fonts to scan by clicking on the &apos;Search Constraints&apos; link.
        ///
        ///Press the &apos;Search&apos; button to scan the fonts installed on this computer for matches. Any matches found will be listed in the &apos;Fonts&apos; table.
        ///
        ///After matches have been found [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YouCanSearchAutomaticallyForFontsWhichMatchTheSelectedRegionSelectARegionAndEnt {
            get {
                return ResourceManager.GetString("YouCanSearchAutomaticallyForFontsWhichMatchTheSelectedRegionSelectARegionAndEnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can search manually for fonts which match the selected region.
        ///
        ///Select a region and enter the text value held in it.
        ///
        ///Select an approximate font size and style and press &apos;Render List&apos; to generate a list of all fonts installed on this computer.
        ///
        ///Select a font in this list to see the entered text rendered in that font with your specified size and style. You can alter the size and style to see the different renderings or select a different region to compare against them.
        ///
        ///Press OK to accept the selected fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YouCanSearchManuallyForFontsWhichMatchTheSelectedRegionSelectARegionAndEnterThe {
            get {
                return ResourceManager.GetString("YouCanSearchManuallyForFontsWhichMatchTheSelectedRegionSelectARegionAndEnterThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a font name.
        /// </summary>
        internal static string YouMustProvideAFontName {
            get {
                return ResourceManager.GetString("YouMustProvideAFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must tick at least one checkbox in each group.
        /// </summary>
        internal static string YouMustTickAtLeastOneCheckboxInEachGroup {
            get {
                return ResourceManager.GetString("YouMustTickAtLeastOneCheckboxInEachGroup", resourceCulture);
            }
        }
    }
}
