'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ctlWorkQueueSnapshots_Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AutomateUI.ctlWorkQueueSnapshots.Resources", GetType(ctlWorkQueueSnapshots_Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enabled.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Enabled() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End time.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Endtime() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Endtime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Friday.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Friday() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Friday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interval.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Interval() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Interval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monday.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Monday() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Monday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Name() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saturday.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Saturday() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Saturday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start time.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Starttime() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Starttime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sunday.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Sunday() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Sunday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thursday.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Thursday() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Thursday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time zone.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Timezone() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Timezone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tuesday.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Tuesday() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Tuesday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wednesday.
        '''</summary>
        Friend Shared ReadOnly Property ConfigurationColumnHeader_Wednesday() As String
            Get
                Return ResourceManager.GetString("ConfigurationColumnHeader_Wednesday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New snapshot configuration.
        '''</summary>
        Friend Shared ReadOnly Property DefaultConfigurationName() As String
            Get
                Return ResourceManager.GetString("DefaultConfigurationName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete configuration &apos;{0}&apos;?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteSnapshotConfigurationConfirmation_Template() As String
            Get
                Return ResourceManager.GetString("DeleteSnapshotConfigurationConfirmation_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to delete snapshot configuration as it is applied to the following work queues; {0}.
        '''</summary>
        Friend Shared ReadOnly Property SnapshotConfigurationAssociatedToWorkQueues_Template() As String
            Get
                Return ResourceManager.GetString("SnapshotConfigurationAssociatedToWorkQueues_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} additional queues not displayed....
        '''</summary>
        Friend Shared ReadOnly Property XNumberOfQueuesNotDisplayed_Template() As String
            Get
                Return ResourceManager.GetString("XNumberOfQueuesNotDisplayed_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must remove these work queues from the snapshot configuration before it can be deleted..
        '''</summary>
        Friend Shared ReadOnly Property YouMustDissociateWorkQueues() As String
            Get
                Return ResourceManager.GetString("YouMustDissociateWorkQueues", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
