
Imports BluePrism.Server.Domain.Models.Attributes

Public Enum WorkQueueSortByProperty
    <ColumnNameSortBy(ColumnName:="name", SortDirection:="asc") >
    NameAsc = 0
    <ColumnNameSortBy(ColumnName:="name", SortDirection:="desc") >
    NameDesc = 1
    <ColumnNameSortBy(ColumnName:="running", SortDirection:="asc") >
    RunningAsc = 2
    <ColumnNameSortBy(ColumnName:="running", SortDirection:="desc") >
    RunningDesc = 3
    <ColumnNameSortBy(ColumnName:="keyfield", SortDirection:="asc") >
    KeyFieldAsc = 4
    <ColumnNameSortBy(ColumnName:="keyfield", SortDirection:="desc") >
    KeyFieldDesc = 5
    <ColumnNameSortBy(ColumnName:="maxattempts", SortDirection:="asc") >
    MaxAttemptsAsc = 6
    <ColumnNameSortBy(ColumnName:="maxattempts", SortDirection:="desc") >
    MaxAttemptsDesc = 7
    <ColumnNameSortBy(ColumnName:="encryptid", SortDirection:="asc") >
    EncryptIdAsc = 8
    <ColumnNameSortBy(ColumnName:="encryptid", SortDirection:="desc") >
    EncryptIdDesc = 9
    <ColumnNameSortBy(ColumnName:="total", SortDirection:="asc") >
    TotalAsc = 10
    <ColumnNameSortBy(ColumnName:="total", SortDirection:="desc") >
    TotalDesc = 11
    <ColumnNameSortBy(ColumnName:="completed", SortDirection:="asc") >
    CompletedAsc = 12
    <ColumnNameSortBy(ColumnName:="completed", SortDirection:="desc") >
    CompletedDesc = 13
    <ColumnNameSortBy(ColumnName:="pending", SortDirection:="asc") >
    PendingAsc = 14
    <ColumnNameSortBy(ColumnName:="pending", SortDirection:="desc") >
    PendingDesc = 15
    <ColumnNameSortBy(ColumnName:="exceptioned", SortDirection:="asc") >
    ExceptionedAsc = 16
    <ColumnNameSortBy(ColumnName:="exceptioned", SortDirection:="desc") >
    ExceptionedDesc = 17
    <ColumnNameSortBy(ColumnName:="totalworktime", SortDirection:="asc") >
    TotalWorkTimeAsc = 18
    <ColumnNameSortBy(ColumnName:="totalworktime", SortDirection:="desc") >
    TotalWorkTimeDesc = 19
    <ColumnNameSortBy(ColumnName:="averageworkedtime", SortDirection:="asc") >
    AverageWorkedTimeAsc = 20
    <ColumnNameSortBy(ColumnName:="averageworkedtime", SortDirection:="desc") >
    AverageWorkedTimeDesc = 21
    <ColumnNameSortBy(ColumnName:="locked", SortDirection:="asc") >
    LockedAsc = 22
    <ColumnNameSortBy(ColumnName:="locked", SortDirection:="desc") >
    LockedDesc = 23
End Enum
