'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BluePrism.Config.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A connection could not be established to the domain {0} from this device. {1}User: {2}{1}{1}Verify that the name is valid and that the domain is accessible to this device.
        '''</summary>
        Friend ReadOnly Property AConnectionCouldNotBeEstablishedToTheDomain0FromThisDevice1User211VerifyThatThe() As String
            Get
                Return ResourceManager.GetString("AConnectionCouldNotBeEstablishedToTheDomain0FromThisDevice1User211VerifyThatThe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A connection was successfully established to the domain {0} from this device. {1}User: {2}.
        '''</summary>
        Friend ReadOnly Property AConnectionWasSuccessfullyEstablishedToTheDomain0FromThisDevice1User2() As String
            Get
                Return ResourceManager.GetString("AConnectionWasSuccessfullyEstablishedToTheDomain0FromThisDevice1User2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Availability Group (SQL Authentication).
        '''</summary>
        Friend ReadOnly Property AvailabilityGroupSQLAuthentication() As String
            Get
                Return ResourceManager.GetString("AvailabilityGroupSQLAuthentication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Availability Group (Windows Authentication).
        '''</summary>
        Friend ReadOnly Property AvailabilityGroupWindowsAuthentication() As String
            Get
                Return ResourceManager.GetString("AvailabilityGroupWindowsAuthentication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Blue Prism Server.
        '''</summary>
        Friend ReadOnly Property BluePrismServer() As String
            Get
                Return ResourceManager.GetString("BluePrismServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot configure this database - {0}.
        '''</summary>
        Friend ReadOnly Property CannotConfigureThisDatabase0() As String
            Get
                Return ResourceManager.GetString("CannotConfigureThisDatabase0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal - unable to open offline database help..
        '''</summary>
        Friend ReadOnly Property CannotOpenOfflineDatabaseHelp() As String
            Get
                Return ResourceManager.GetString("CannotOpenOfflineDatabaseHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configure Database.
        '''</summary>
        Friend ReadOnly Property ConfigureDatabase() As String
            Get
                Return ResourceManager.GetString("ConfigureDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection Failed.
        '''</summary>
        Friend ReadOnly Property ConnectionFailed() As String
            Get
                Return ResourceManager.GetString("ConnectionFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Connection.
        '''</summary>
        Friend ReadOnly Property ConnectionManagerPanel_Default_Connection() As String
            Get
                Return ResourceManager.GetString("ConnectionManagerPanel_Default_Connection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection {0}.
        '''</summary>
        Friend ReadOnly Property ConnectionManagerPanel_unique_connection_format() As String
            Get
                Return ResourceManager.GetString("ConnectionManagerPanel_unique_connection_format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection Name.
        '''</summary>
        Friend ReadOnly Property ConnectionName() As String
            Get
                Return ResourceManager.GetString("ConnectionName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection Successful.
        '''</summary>
        Friend ReadOnly Property ConnectionSuccessful() As String
            Get
                Return ResourceManager.GetString("ConnectionSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection valid..
        '''</summary>
        Friend ReadOnly Property ConnectionValid() As String
            Get
                Return ResourceManager.GetString("ConnectionValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Control in row 1 must be the caption label - attempted to set to: {0}.
        '''</summary>
        Friend ReadOnly Property ControlInRow1MustBeTheCaptionLabelAttemptedToSetTo0() As String
            Get
                Return ResourceManager.GetString("ControlInRow1MustBeTheCaptionLabelAttemptedToSetTo0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copy_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not save local machine configuration: {0}.
        '''</summary>
        Friend ReadOnly Property CouldNotSaveLocalMachineConfiguration0() As String
            Get
                Return ResourceManager.GetString("CouldNotSaveLocalMachineConfiguration0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not write to configuration file - {0}.
        '''</summary>
        Friend ReadOnly Property CouldNotWriteToConfigurationFile0() As String
            Get
                Return ResourceManager.GetString("CouldNotWriteToConfigurationFile0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creating Database.
        '''</summary>
        Friend ReadOnly Property CreateDatabaseForm_CreatingDatabase() As String
            Get
                Return ResourceManager.GetString("CreateDatabaseForm_CreatingDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property database_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property database_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database configured.
        '''</summary>
        Friend ReadOnly Property DatabaseConfigured() As String
            Get
                Return ResourceManager.GetString("DatabaseConfigured", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database created..
        '''</summary>
        Friend ReadOnly Property DatabaseCreated() As String
            Get
                Return ResourceManager.GetString("DatabaseCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Database Already Exists.
        '''</summary>
        Friend ReadOnly Property DatabaseExistsCaption() As String
            Get
                Return ResourceManager.GetString("DatabaseExistsCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The database {0} already exists, are you sure you want to overwrite it?.
        '''</summary>
        Friend ReadOnly Property DatabaseExistsDoYouWantToOverwrite() As String
            Get
                Return ResourceManager.GetString("DatabaseExistsDoYouWantToOverwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Name.
        '''</summary>
        Friend ReadOnly Property DatabaseName() As String
            Get
                Return ResourceManager.GetString("DatabaseName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Server.
        '''</summary>
        Friend ReadOnly Property DatabaseServer() As String
            Get
                Return ResourceManager.GetString("DatabaseServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database valid..
        '''</summary>
        Friend ReadOnly Property DatabaseValid() As String
            Get
                Return ResourceManager.GetString("DatabaseValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detail &gt;&gt;.
        '''</summary>
        Friend ReadOnly Property Detail() As String
            Get
                Return ResourceManager.GetString("Detail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distribution Group.
        '''</summary>
        Friend ReadOnly Property DistributionGroup() As String
            Get
                Return ResourceManager.GetString("DistributionGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ensure that the connection mode configured on the client matches the connection mode configured on the server.
        '''</summary>
        Friend ReadOnly Property EnsureThatTheConnectionModeConfiguredOnTheClientMatchesTheConnectionModeConfigu() As String
            Get
                Return ResourceManager.GetString("EnsureThatTheConnectionModeConfiguredOnTheClientMatchesTheConnectionModeConfigu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ensure that the selected connection mode matches the configured connection mode on the server.
        '''</summary>
        Friend ReadOnly Property EnsureThatTheSelectedConnectionModeMatchesTheConfiguredConnectionModeOnTheServer() As String
            Get
                Return ResourceManager.GetString("EnsureThatTheSelectedConnectionModeMatchesTheConfiguredConnectionModeOnTheServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ensure that the specified server address matches the binding configured on the server.
        '''</summary>
        Friend ReadOnly Property EnsureThatTheSpecifiedServerAddressMatchesTheBindingConfiguredOnTheServer() As String
            Get
                Return ResourceManager.GetString("EnsureThatTheSpecifiedServerAddressMatchesTheBindingConfiguredOnTheServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the distinguished name (DN) to search from. When left blank the whole domain is searched..
        '''</summary>
        Friend ReadOnly Property EnterTheDistinguishedNameDNToSearchFromWhenLeftBlankTheWholeDomainIsSearched() As String
            Get
                Return ResourceManager.GetString("EnterTheDistinguishedNameDNToSearchFromWhenLeftBlankTheWholeDomainIsSearched", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error finding groups.
        '''</summary>
        Friend ReadOnly Property ErrorFindingGroups() As String
            Get
                Return ResourceManager.GetString("ErrorFindingGroups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error in connection configuration form: {0}.
        '''</summary>
        Friend ReadOnly Property ErrorInConnectionConfigurationForm0() As String
            Get
                Return ResourceManager.GetString("ErrorInConnectionConfigurationForm0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error loading configuration options: {0}.
        '''</summary>
        Friend ReadOnly Property ErrorLoadingConfigurationOptions0() As String
            Get
                Return ResourceManager.GetString("ErrorLoadingConfigurationOptions0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to configure database - {0} - see details.
        '''</summary>
        Friend ReadOnly Property FailedToConfigureDatabase0() As String
            Get
                Return ResourceManager.GetString("FailedToConfigureDatabase0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to create database - {0} - see details.
        '''</summary>
        Friend ReadOnly Property FailedToCreateDatabase0() As String
            Get
                Return ResourceManager.GetString("FailedToCreateDatabase0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to read session log size details. Please ensure you enter the correct database credentials.
        '''</summary>
        Friend ReadOnly Property FailedToReadSessionLogSizeDetails() As String
            Get
                Return ResourceManager.GetString("FailedToReadSessionLogSizeDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter text is not a valid SID.
        '''</summary>
        Friend ReadOnly Property FilterTextIsNotAValidSID() As String
            Get
                Return ResourceManager.GetString("FilterTextIsNotAValidSID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following error has occurred:{0}{1}.
        '''</summary>
        Friend ReadOnly Property FollowingErrorHasOccuredMessage() As String
            Get
                Return ResourceManager.GetString("FollowingErrorHasOccuredMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide &lt;&lt;.
        '''</summary>
        Friend ReadOnly Property Hide() As String
            Get
                Return ResourceManager.GetString("Hide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incorrect password.
        '''</summary>
        Friend ReadOnly Property IncorrectPassword() As String
            Get
                Return ResourceManager.GetString("IncorrectPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal error - {0}.
        '''</summary>
        Friend ReadOnly Property InternalError0() As String
            Get
                Return ResourceManager.GetString("InternalError0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter valid Additional SQL Connection Parameters, or clear the field..
        '''</summary>
        Friend ReadOnly Property InvalidAdditionalSqlParametersEntered() As String
            Get
                Return ResourceManager.GetString("InvalidAdditionalSqlParametersEntered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid column/row for caption control: col:{0} row:{1}.
        '''</summary>
        Friend ReadOnly Property InvalidColumnRowForCaptionControlCol0Row1() As String
            Get
                Return ResourceManager.GetString("InvalidColumnRowForCaptionControlCol0Row1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Using Windows locale settings.
        '''</summary>
        Friend ReadOnly Property LocaleConfigForm_UsingWindowsLocaleSettings() As String
            Get
                Return ResourceManager.GetString("LocaleConfigForm_UsingWindowsLocaleSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows locale settings.
        '''</summary>
        Friend ReadOnly Property LocaleConfigForm_WindowsLocaleSettings() As String
            Get
                Return ResourceManager.GetString("LocaleConfigForm_WindowsLocaleSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No upgrade is available at this time.
        '''</summary>
        Friend ReadOnly Property NoUpgradeIsAvailableAtThisTime() As String
            Get
                Return ResourceManager.GetString("NoUpgradeIsAvailableAtThisTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend ReadOnly Property Password() As String
            Get
                Return ResourceManager.GetString("Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PID: {0} does not represent a running process.
        '''</summary>
        Friend ReadOnly Property PID0DoesNotRepresentARunningProcess() As String
            Get
                Return ResourceManager.GetString("PID0DoesNotRepresentARunningProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please complete these fields..
        '''</summary>
        Friend ReadOnly Property PleaseCompleteTheseFields() As String
            Get
                Return ResourceManager.GetString("PleaseCompleteTheseFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please fill in all connection details before testing the connection..
        '''</summary>
        Friend ReadOnly Property PleaseFillInAllConnectionDetailsBeforeTestingTheConnection() As String
            Get
                Return ResourceManager.GetString("PleaseFillInAllConnectionDetailsBeforeTestingTheConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please first select a connection to delete..
        '''</summary>
        Friend ReadOnly Property PleaseFirstSelectAConnectionToDelete() As String
            Get
                Return ResourceManager.GetString("PleaseFirstSelectAConnectionToDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prism_full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prism_full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Error.
        '''</summary>
        Friend ReadOnly Property SaveError() As String
            Get
                Return ResourceManager.GetString("SaveError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Security Group.
        '''</summary>
        Friend ReadOnly Property SecurityGroup() As String
            Get
                Return ResourceManager.GetString("SecurityGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select the group to be assigned to the {0} role.
        '''</summary>
        Friend ReadOnly Property SelectTheGroupToBeAssignedToThe0Role() As String
            Get
                Return ResourceManager.GetString("SelectTheGroupToBeAssignedToThe0Role", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Semi-colon separated parameters to add to the connection string.
        '''</summary>
        Friend ReadOnly Property SemiColonSeparatedParametersToAddToTheConnectionString() As String
            Get
                Return ResourceManager.GetString("SemiColonSeparatedParametersToAddToTheConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL Server (Custom Connection String).
        '''</summary>
        Friend ReadOnly Property SQLServerCustomConnectionString() As String
            Get
                Return ResourceManager.GetString("SQLServerCustomConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL Server (SQL Authentication).
        '''</summary>
        Friend ReadOnly Property SQLServerSQLAuthentication() As String
            Get
                Return ResourceManager.GetString("SQLServerSQLAuthentication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL Server (Windows Authentication).
        '''</summary>
        Friend ReadOnly Property SQLServerWindowsAuthentication() As String
            Get
                Return ResourceManager.GetString("SQLServerWindowsAuthentication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The complete SQL connection string to use.
        '''</summary>
        Friend ReadOnly Property TheCompleteSQLConnectionStringToUse() As String
            Get
                Return ResourceManager.GetString("TheCompleteSQLConnectionStringToUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The database user name to use.
        '''</summary>
        Friend ReadOnly Property TheDatabaseUserNameToUse() As String
            Get
                Return ResourceManager.GetString("TheDatabaseUserNameToUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The database will be configured according to the settings you supply below. Once set, these cannot be changed without rebuilding the database..
        '''</summary>
        Friend ReadOnly Property TheDatabaseWillBeConfiguredAccordingToTheSettingsYouSupplyBelowOnceSetTheseCann() As String
            Get
                Return ResourceManager.GetString("TheDatabaseWillBeConfiguredAccordingToTheSettingsYouSupplyBelowOnceSetTheseCann", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The group {0} cannot be found as it may have been removed from this domain. Please contact your Active Directory Domain Administrator..
        '''</summary>
        Friend ReadOnly Property TheGroup0CannotBeFoundAsItMayHaveBeenRemovedFromThisDomainPleaseContactYourActi() As String
            Get
                Return ResourceManager.GetString("TheGroup0CannotBeFoundAsItMayHaveBeenRemovedFromThisDomainPleaseContactYourActi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The group {0} cannot be found in the domain {1}.{2}Please contact your Active Directory Domain Administrator..
        '''</summary>
        Friend ReadOnly Property TheGroup0CannotBeFoundInTheDomain12PleaseContactYourActiveDirectoryDomainAdmini() As String
            Get
                Return ResourceManager.GetString("TheGroup0CannotBeFoundInTheDomain12PleaseContactYourActiveDirectoryDomainAdmini", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The hostname of the Blue Prism Server.
        '''</summary>
        Friend ReadOnly Property TheHostnameOfTheBluePrismServer() As String
            Get
                Return ResourceManager.GetString("TheHostnameOfTheBluePrismServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The hostname of the database server.
        '''</summary>
        Friend ReadOnly Property TheHostnameOfTheDatabaseServer() As String
            Get
                Return ResourceManager.GetString("TheHostnameOfTheDatabaseServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name by which this connection will be remembered.
        '''</summary>
        Friend ReadOnly Property TheNameByWhichThisConnectionWillBeRemembered() As String
            Get
                Return ResourceManager.GetString("TheNameByWhichThisConnectionWillBeRemembered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the database to connect to.
        '''</summary>
        Friend ReadOnly Property TheNameOfTheDatabaseToConnectTo() As String
            Get
                Return ResourceManager.GetString("TheNameOfTheDatabaseToConnectTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of this connection is not unique. Please choose another.
        '''</summary>
        Friend ReadOnly Property TheNameOfThisConnectionIsNotUniquePleaseChooseAnother() As String
            Get
                Return ResourceManager.GetString("TheNameOfThisConnectionIsNotUniquePleaseChooseAnother", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The password of the user named above.
        '''</summary>
        Friend ReadOnly Property ThePasswordOfTheUserNamedAbove() As String
            Get
                Return ResourceManager.GetString("ThePasswordOfTheUserNamedAbove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The password that you entered does not match the password entered in the &apos;connections&apos; dialog (available from the main menu).{0}{1}Please check your password and try again..
        '''</summary>
        Friend ReadOnly Property ThePasswordThatYouEnteredDoesNotMatchThePasswordEnteredInTheConnectionsDialogAv() As String
            Get
                Return ResourceManager.GetString("ThePasswordThatYouEnteredDoesNotMatchThePasswordEnteredInTheConnectionsDialogAv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The port on this device which receives callback communication.
        '''</summary>
        Friend ReadOnly Property ThePortOnThisDeviceWhichReceivesCallbackCommunication() As String
            Get
                Return ResourceManager.GetString("ThePortOnThisDeviceWhichReceivesCallbackCommunication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The type of connection to use.
        '''</summary>
        Friend ReadOnly Property TheTypeOfConnectionToUse() As String
            Get
                Return ResourceManager.GetString("TheTypeOfConnectionToUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This database is already configured..
        '''</summary>
        Friend ReadOnly Property ThisDatabaseIsAlreadyConfigured() As String
            Get
                Return ResourceManager.GetString("ThisDatabaseIsAlreadyConfigured", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This must match the listening port configured on the Blue Prism Server(s).
        '''</summary>
        Friend ReadOnly Property ThisMustMatchTheListeningPortConfiguredOnTheBluePrismServerS() As String
            Get
                Return ResourceManager.GetString("ThisMustMatchTheListeningPortConfiguredOnTheBluePrismServerS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This must match the mode configured on the Blue Prism Server(s).
        '''</summary>
        Friend ReadOnly Property ThisMustMatchTheModeConfiguredOnTheBluePrismServerS() As String
            Get
                Return ResourceManager.GetString("ThisMustMatchTheModeConfiguredOnTheBluePrismServerS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property triangle_fwd_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("triangle_fwd_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Friend ReadOnly Property Unknown() As String
            Get
                Return ResourceManager.GetString("Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelled. Rolling back.
        '''</summary>
        Friend ReadOnly Property UpgradeCancelled() As String
            Get
                Return ResourceManager.GetString("UpgradeCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelling. Please wait..
        '''</summary>
        Friend ReadOnly Property UpgradeCancelling() As String
            Get
                Return ResourceManager.GetString("UpgradeCancelling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upgrading database.
        '''</summary>
        Friend ReadOnly Property UpgradeDatabase() As String
            Get
                Return ResourceManager.GetString("UpgradeDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot upgrade the database at this time. This may be due to another user currently executing a long-running transaction on this database..
        '''</summary>
        Friend ReadOnly Property UpgradeDatabaseForm_CannotAccessDatabase() As String
            Get
                Return ResourceManager.GetString("UpgradeDatabaseForm_CannotAccessDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Database cannot be upgraded until the previous attempt has been completed or rolled back..
        '''</summary>
        Friend ReadOnly Property UpgradeDatabaseForm_DatabaseUpgradeTransactionInProgress() As String
            Get
                Return ResourceManager.GetString("UpgradeDatabaseForm_DatabaseUpgradeTransactionInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upgrade failed - {0}.
        '''</summary>
        Friend ReadOnly Property UpgradeFailed0() As String
            Get
                Return ResourceManager.GetString("UpgradeFailed0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upgrade succeeded.
        '''</summary>
        Friend ReadOnly Property UpgradeSucceeded() As String
            Get
                Return ResourceManager.GetString("UpgradeSucceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usage: automateconfig [options]\nOptions:\n  ? | help | /h      : Show this help\n  connections        : Shows the database configuration dialog\n                       This is the default if no option is given\n  mksrc {sourcename} : Creates an event log source within the\n                       Blue Prism event log, if it does not\n                       already exist\n  daemon {procid}    : Starts the automateconfig writer daemon for\n                       the given process id.
        '''</summary>
        Friend ReadOnly Property usage_help() As String
            Get
                Return ResourceManager.GetString("usage_help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usage: AutomateConfig daemon {process-id}.
        '''</summary>
        Friend ReadOnly Property UsageAutomateConfigDaemonProcessId() As String
            Get
                Return ResourceManager.GetString("UsageAutomateConfigDaemonProcessId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usage: AutomateConfig mksrc {sourcename}.
        '''</summary>
        Friend ReadOnly Property UsageAutomateConfigMksrcSourcename() As String
            Get
                Return ResourceManager.GetString("UsageAutomateConfigMksrcSourcename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserID.
        '''</summary>
        Friend ReadOnly Property UserID() As String
            Get
                Return ResourceManager.GetString("UserID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verify that the certificate on the server has been appropriately configured and is valid for the specified server address.
        '''</summary>
        Friend ReadOnly Property VerifyThatTheCertificateOnTheServerHasBeenAppropriatelyConfiguredAndIsValidForT() As String
            Get
                Return ResourceManager.GetString("VerifyThatTheCertificateOnTheServerHasBeenAppropriatelyConfiguredAndIsValidForT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property xError() As String
            Get
                Return ResourceManager.GetString("xError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can use the wildcard operator (*) when filtering by name,{0}to represent a value that could be equal to anything. For{0}example, searching for La* would return all groups with names{0}beginning with La, and searching *Admin* would return all{0}groups containing Admin..
        '''</summary>
        Friend ReadOnly Property YouCanUseTheWildcardOperatorWhenFilteringByName0ToRepresentAValueThatCouldBeEqu() As String
            Get
                Return ResourceManager.GetString("YouCanUseTheWildcardOperatorWhenFilteringByName0ToRepresentAValueThatCouldBeEqu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You may not delete the last connection. However you may rename it and change all of its other properties if you wish..
        '''</summary>
        Friend ReadOnly Property YouMayNotDeleteTheLastConnectionHoweverYouMayRenameItAndChangeAllOfItsOtherProp() As String
            Get
                Return ResourceManager.GetString("YouMayNotDeleteTheLastConnectionHoweverYouMayRenameItAndChangeAllOfItsOtherProp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter a valid connection name. The name may not be blank..
        '''</summary>
        Friend ReadOnly Property YouMustEnterAValidConnectionNameTheNameMayNotBeBlank() As String
            Get
                Return ResourceManager.GetString("YouMustEnterAValidConnectionNameTheNameMayNotBeBlank", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
