'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BluePrism.Server.Domain.Models.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The active queue &apos;{0}&apos; is already locked under the name &apos;{1}&apos;, last seen at {2}.
        '''</summary>
        Friend ReadOnly Property ActiveQueueLockFailedException_TheActiveQueue0IsAlreadyLockedUnderTheName1LastSeenAt2() As String
            Get
                Return ResourceManager.GetString("ActiveQueueLockFailedException_TheActiveQueue0IsAlreadyLockedUnderTheName1LastSee"& _ 
                        "nAt2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while writing an audit record: {0}.
        '''</summary>
        Friend ReadOnly Property AuditOperationFailedException_AnErrorOccurredWhileWritingAnAuditRecord0() As String
            Get
                Return ResourceManager.GetString("AuditOperationFailedException_AnErrorOccurredWhileWritingAnAuditRecord0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The queue item &apos;{0}&apos; is deferred..
        '''</summary>
        Friend ReadOnly Property DeferredQueueItemException() As String
            Get
                Return ResourceManager.GetString("DeferredQueueItemException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File &apos;{0}&apos; already exists - cannot create it.
        '''</summary>
        Friend ReadOnly Property FileAlreadyExistsException_File0AlreadyExistsCannotCreateIt() As String
            Get
                Return ResourceManager.GetString("FileAlreadyExistsException_File0AlreadyExistsCannotCreateIt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client version {0} is not compatible with server version {1}.
        '''</summary>
        Friend ReadOnly Property IncompatibleApiException_ClientVersionIsNotCompatibleWithServerVersion() As String
            Get
                Return ResourceManager.GetString("IncompatibleApiException_ClientVersionIsNotCompatibleWithServerVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client version {0}, Server version {1}.
        '''</summary>
        Friend ReadOnly Property IncompatibleApiException_DetailClientVersionServerVersion() As String
            Get
                Return ResourceManager.GetString("IncompatibleApiException_DetailClientVersionServerVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The username or password is incorrect. Please try again..
        '''</summary>
        Friend ReadOnly Property IncorrectLoginException_TheUsernameOrPasswordIsIncorrectPleaseTryAgain() As String
            Get
                Return ResourceManager.GetString("IncorrectLoginException_TheUsernameOrPasswordIsIncorrectPleaseTryAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The queue item &apos;{0}&apos; is locked..
        '''</summary>
        Friend ReadOnly Property LockedQueueItemException() As String
            Get
                Return ResourceManager.GetString("LockedQueueItemException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credential master key was not found.
        '''</summary>
        Friend ReadOnly Property MissingCredentialMasterKeyException_CredentialMasterKeyWasNotFound() As String
            Get
                Return ResourceManager.GetString("MissingCredentialMasterKeyException_CredentialMasterKeyWasNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not find &quot;{0}&quot;.
        '''</summary>
        Friend ReadOnly Property MissingXmlObjectException_CouldNotFind0() As String
            Get
                Return ResourceManager.GetString("MissingXmlObjectException_CouldNotFind0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dashboard with ID {0} not found..
        '''</summary>
        Friend ReadOnly Property NoSuchDashboardException_DashboardWithID0NotFound() As String
            Get
                Return ResourceManager.GetString("NoSuchDashboardException_DashboardWithID0NotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The permission &apos;{0}&apos; does not exist.
        '''</summary>
        Friend ReadOnly Property NoSuchPermissionException_ThePermission0DoesNotExist() As String
            Get
                Return ResourceManager.GetString("NoSuchPermissionException_ThePermission0DoesNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The queue with name &apos;{0}&apos; was not found.
        '''</summary>
        Friend ReadOnly Property NoSuchQueueException_TheQueueWithName0WasNotFound() As String
            Get
                Return ResourceManager.GetString("NoSuchQueueException_TheQueueWithName0WasNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The queue item &apos;{0}&apos; was not found..
        '''</summary>
        Friend ReadOnly Property NoSuchQueueItemException() As String
            Get
                Return ResourceManager.GetString("NoSuchQueueItemException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resource PC not found.
        '''</summary>
        Friend ReadOnly Property NoSuchResourceException_ResourcePCNotFound() As String
            Get
                Return ResourceManager.GetString("NoSuchResourceException_ResourcePCNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The session with ID &apos;{0}&apos; was not found.
        '''</summary>
        Friend ReadOnly Property NoSuchSessionException_TheSessionWithID0WasNotFound() As String
            Get
                Return ResourceManager.GetString("NoSuchSessionException_TheSessionWithID0WasNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No work item was found with the ID: {0}.
        '''</summary>
        Friend ReadOnly Property NoSuchWorkItemException_NoWorkItemWasFoundWithTheID0() As String
            Get
                Return ResourceManager.GetString("NoSuchWorkItemException_NoWorkItemWasFoundWithTheID0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No work item was found with the ident: {0}.
        '''</summary>
        Friend ReadOnly Property NoSuchWorkItemException_NoWorkItemWasFoundWithTheIdent0() As String
            Get
                Return ResourceManager.GetString("NoSuchWorkItemException_NoWorkItemWasFoundWithTheIdent0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The queue item &apos;{0}&apos; is not in an active state..
        '''</summary>
        Friend ReadOnly Property NotActiveQueueItemException() As String
            Get
                Return ResourceManager.GetString("NotActiveQueueItemException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No connection to Resource PC.
        '''</summary>
        Friend ReadOnly Property NotConnectedException_NoConnectionToResourcePC() As String
            Get
                Return ResourceManager.GetString("NotConnectedException_NoConnectionToResourcePC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No valid token found.
        '''</summary>
        Friend ReadOnly Property NoValidTokenFoundException_NoValidTokenFound() As String
            Get
                Return ResourceManager.GetString("NoValidTokenFoundException_NoValidTokenFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;none&gt;.
        '''</summary>
        Friend ReadOnly Property PermissionException_None() As String
            Get
                Return ResourceManager.GetString("PermissionException_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must have the following permissions to perform this action :.
        '''</summary>
        Friend ReadOnly Property PermissionException_YouMustHaveTheFollowingPermissionsToPerformThisAction() As String
            Get
                Return ResourceManager.GetString("PermissionException_YouMustHaveTheFollowingPermissionsToPerformThisAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The operation could not be completed because the queue &apos;{0}&apos; is not empty.
        '''</summary>
        Friend ReadOnly Property QueueNotEmptyException_TheOperationCouldNotBeCompletedBecauseTheQueue0IsNotEmpty() As String
            Get
                Return ResourceManager.GetString("QueueNotEmptyException_TheOperationCouldNotBeCompletedBecauseTheQueue0IsNotEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A required resource was unavailable.
        '''</summary>
        Friend ReadOnly Property ResourceUnavailableException_ARequiredResourceWasUnavailable() As String
            Get
                Return ResourceManager.GetString("ResourceUnavailableException_ARequiredResourceWasUnavailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restoring a session log failed because a session with that ID already exists.
        '''</summary>
        Friend ReadOnly Property SessionAlreadyExistsException_RestoringASessionLogFailedBecauseASessionWithThatIDAlreadyExists() As String
            Get
                Return ResourceManager.GetString("SessionAlreadyExistsException_RestoringASessionLogFailedBecauseASessionWithThatID"& _ 
                        "AlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reached a supposedly unreachable part of the program.
        '''</summary>
        Friend ReadOnly Property UnreachableException_ReachedASupposedlyUnreachablePartOfTheProgram() As String
            Get
                Return ResourceManager.GetString("UnreachableException_ReachedASupposedlyUnreachablePartOfTheProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The user could not be found in the database..
        '''</summary>
        Friend ReadOnly Property UserNotFoundException_TheUserCouldNotBeFoundInTheDatabase() As String
            Get
                Return ResourceManager.GetString("UserNotFoundException_TheUserCouldNotBeFoundInTheDatabase", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
