namespace BluePrism.Api.IntegrationTests
{
    public class PermissionList
    {
        public static string[] Permissions => new[]
        {
            "Audit - Alerts",
            "Audit - Audit Logs",
            "Audit - Business Object Logs",
            "Audit - Configure Design Controls",
            "Audit - Process Logs",
            "Audit - Statistics",
            "Audit - View Design Controls",
            "Authenticate as Resource",
            "Business Objects - Configure Environment Variables",
            "Business Objects - Exception Types",
            "Business Objects - Exposure",
            "Business Objects - External",
            "Business Objects - History",
            "Business Objects - Management",
            "Business Objects - SOAP Web Services",
            "Business Objects - View Environment Variables",
            "Business Objects - Web API Services",
            "Business Objects - Web Connection Settings",
            "Configure Process Alerts",
            "Configure Resource",
            "Control Resource",
            "Create Business Object",
            "Create Process",
            "Create Release",
            "Create Schedule",
            "Create/Edit Package",
            "Create/Edit/Delete Tiles",
            "CreateBatchType",
            "CreateDocumentType",
            "CreateFieldTemplate",
            "CreateUserAccount",
            "Data Gateways - Advanced Configuration",
            "Data Gateways - Configuration",
            "Data Gateways - Control Room",
            "Decipher - Configuration",
            "Decipher - Create Batch",
            "Decipher - Redirect Output",
            "Decipher - View Document",
            "Decipher - View Document Data",
            "Delete Business Object",
            "Delete Package",
            "Delete Process",
            "Delete Schedule",
            "DeleteBatch",
            "DeleteBatchType",
            "DeleteDocumentType",
            "DeleteFieldTemplate",
            "Design Global Dashboards",
            "Design Personal Dashboards",
            "Design Published Dashboards",
            "Edit Business Object",
            "Edit Object Groups",
            "Edit Process",
            "Edit Process Groups",
            "Edit Resource Groups",
            "Edit Schedule",
            "Execute Business Object",
            "Execute Business Object as Web Service",
            "Execute Process",
            "Execute Process as Web Service",
            "Export Business Object",
            "Export Process",
            "Full Access to Queue Management",
            "Import Business Object",
            "Import Global Dashboard",
            "Import Process",
            "Import Published Dashboard",
            "Import Release",
            "Import Skill",
            "Import Tile",
            "Manage Business Object Access Rights",
            "Manage Process Access Rights",
            "Manage Resource Access Rights",
            "Manage Skill",
            "ModifyBatchType",
            "ModifyDocument",
            "ModifyDocumentType",
            "ModifyFieldTemplate",
            "ModifyFormData",
            "Processes - Configure Environment Variables",
            "Processes - Exception Types",
            "Processes - Exposure",
            "Processes - Grouping",
            "Processes - History",
            "Processes - Management",
            "Processes - View Environment Variables",
            "Read Access to Queue Management",
            "Resources - Pools",
            "Retire Schedule",
            "Security - Manage Credentials",
            "Security - Manage Encryption Schemes",
            "Security - Sign-on Settings",
            "Security - User Roles",
            "Security - Users",
            "Security - View Encryption Scheme Configuration",
            "Subscribe to Process Alerts",
            "System - Archiving",
            "System - Calendars",
            "System - Fonts",
            "System - License",
            "System - Reporting",
            "System - Scheduler",
            "System - Settings",
            "VerifyBatch",
            "View Business Object Definition",
            "View Dashboards",
            "View Process Definition",
            "View Release Manager",
            "View Resource",
            "View Resource Screen Captures",
            "View Resource Details",
            "View Schedule",
            "View Skill",
            "ViewBatch",
            "ViewBatchOutput",
            "ViewBatchType",
            "ViewDocumentType",
            "ViewFieldTemplate",
            "ViewPage",
            "ViewUserAccount",
            "Workflow - Environment Locking",
            "Workflow - Work Queue Configuration",
        };
    }
}
