//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internationalisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Internationalisation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Queues.
        /// </summary>
        internal static string ctlControlRoom_tv_active_queues {
            get {
                return ResourceManager.GetString("ctlControlRoom_tv_active_queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Gateways.
        /// </summary>
        internal static string ctlControlRoom_tv_data_gateways {
            get {
                return ResourceManager.GetString("ctlControlRoom_tv_data_gateways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Management.
        /// </summary>
        internal static string ctlControlRoom_tv_queue_management {
            get {
                return ResourceManager.GetString("ctlControlRoom_tv_queue_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ctlControlRoom_tv_reports {
            get {
                return ResourceManager.GetString("ctlControlRoom_tv_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retired Schedules.
        /// </summary>
        internal static string ctlControlRoom_tv_retired_schedules {
            get {
                return ResourceManager.GetString("ctlControlRoom_tv_retired_schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        internal static string ctlControlRoom_tv_scheduler {
            get {
                return ResourceManager.GetString("ctlControlRoom_tv_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        internal static string ctlControlRoom_tv_schedules {
            get {
                return ResourceManager.GetString("ctlControlRoom_tv_schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Management.
        /// </summary>
        internal static string ctlControlRoom_tv_session_management {
            get {
                return ResourceManager.GetString("ctlControlRoom_tv_session_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ctlControlRoom_tv_session_today {
            get {
                return ResourceManager.GetString("ctlControlRoom_tv_session_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetables.
        /// </summary>
        internal static string ctlControlRoom_tv_timetables {
            get {
                return ResourceManager.GetString("ctlControlRoom_tv_timetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save settings: {0}.
        /// </summary>
        internal static string ctlDataPipelineSettings_failedToSaveSettings_template {
            get {
                return ResourceManager.GetString("ctlDataPipelineSettings_failedToSaveSettings_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enable at least one option for session logging..
        /// </summary>
        internal static string ctlDataPipelineSettings_InvalidSettings {
            get {
                return ResourceManager.GetString("ctlDataPipelineSettings_InvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Overview.
        /// </summary>
        internal static string ctlPackageTree_tv_package_overview {
            get {
                return ResourceManager.GetString("ctlPackageTree_tv_package_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string ctlsystemmanager_tv_alerts {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving.
        /// </summary>
        internal static string ctlsystemmanager_tv_archiving {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_archiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        internal static string ctlsystemmanager_tv_audit {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Logs.
        /// </summary>
        internal static string ctlsystemmanager_tv_audit_logs {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_audit_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string ctlsystemmanager_tv_calendar {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ctlsystemmanager_tv_configuration {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Wizard.
        /// </summary>
        internal static string ctlsystemmanager_tv_configuration_wizard {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_configuration_wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string ctlsystemmanager_tv_credentials {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Gateways.
        /// </summary>
        internal static string ctlsystemmanager_tv_data_gateways {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_data_gateways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Control.
        /// </summary>
        internal static string ctlsystemmanager_tv_design_control {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_design_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ctlsystemmanager_tv_dg_settings {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_dg_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decipher.
        /// </summary>
        internal static string ctlsystemmanager_tv_documentprocessing {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_documentprocessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Schemes.
        /// </summary>
        internal static string ctlsystemmanager_tv_encryption_schemes {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_encryption_schemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Locks.
        /// </summary>
        internal static string ctlsystemmanager_tv_env_locks {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_env_locks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Variables.
        /// </summary>
        internal static string ctlsystemmanager_tv_env_variables {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_env_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Types.
        /// </summary>
        internal static string ctlsystemmanager_tv_exception_types {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_exception_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure.
        /// </summary>
        internal static string ctlsystemmanager_tv_exposure {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_exposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        internal static string ctlsystemmanager_tv_external {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string ctlsystemmanager_tv_fonts {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string ctlsystemmanager_tv_history {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string ctlsystemmanager_tv_license {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string ctlsystemmanager_tv_management {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Logs.
        /// </summary>
        internal static string ctlsystemmanager_tv_object_logs {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_object_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string ctlsystemmanager_tv_objects {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pools.
        /// </summary>
        internal static string ctlsystemmanager_tv_pools {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_pools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Logs.
        /// </summary>
        internal static string ctlsystemmanager_tv_process_logs {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_process_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        internal static string ctlsystemmanager_tv_processes {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string ctlsystemmanager_tv_reporting {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string ctlsystemmanager_tv_resources {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        internal static string ctlsystemmanager_tv_scheduler {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string ctlsystemmanager_tv_security {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ctlsystemmanager_tv_settings {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-on Settings.
        /// </summary>
        internal static string ctlsystemmanager_tv_sign_on_settings {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_sign_on_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string ctlsystemmanager_tv_skills {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string ctlsystemmanager_tv_skills_management {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_skills_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOAP Web Services.
        /// </summary>
        internal static string ctlsystemmanager_tv_soap_web_services {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_soap_web_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string ctlsystemmanager_tv_statistics {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ctlsystemmanager_tv_system {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        internal static string ctlsystemmanager_tv_user_roles {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_user_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string ctlsystemmanager_tv_users {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        internal static string ctlsystemmanager_tv_web_connection_settings {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_web_connection_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web API Services.
        /// </summary>
        internal static string ctlsystemmanager_tv_webapi_services {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_webapi_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Queue Snapshots.
        /// </summary>
        internal static string ctlsystemmanager_tv_work_queue_snapshots {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_work_queue_snapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Queues.
        /// </summary>
        internal static string ctlsystemmanager_tv_work_queues {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_work_queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        internal static string ctlsystemmanager_tv_workflow {
            get {
                return ResourceManager.GetString("ctlsystemmanager_tv_workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string frmInspect_tv_desktop {
            get {
                return ResourceManager.GetString("frmInspect_tv_desktop", resourceCulture);
            }
        }
    }
}
