Public Enum UserEventCode
    <EventCode("U001","EventCodeAttribute_TheUser0CreatedANewUserWithName1")>
    CreateUser
    <EventCode("U002","EventCodeAttribute_TheUser0DeletedTheUser1FromTheSystem")>
    DeleteUser
    <EventCode("U003","EventCodeAttribute_TheUser0ClonedTheUser1")>
    CloneUser
    <EventCode("U004","EventCodeAttribute_TheUser0ResetThePasswordOfTheUser1")>
    ResetPassword
    <EventCode("U005","EventCodeAttribute_TheUser0RenamedTheUser2To1")>
    RenameUser
    <EventCode("U006","EventCodeAttribute_TheUser0ChangedTheRolesPermissionsOfTheUser1")>
    ChangeRoles
    <EventCode("U007","EventCodeAttribute_TheUser0ChangedThePasswordExpiryOfTheUser1")>
    PasswordExpiry
    <EventCode("U008","EventCodeAttribute_TheUser0ChangedTheAccountExpiryOfTheUser1")>
    UserExpiry
    <EventCode("U009","EventCodeAttribute_TheUser0UnlockedTheAccountOfUser1")>
    UserUnlocked
    <EventCode("U010","EventCodeAttribute_TheUser0MappedTheAccountOfUser1ToTheExternalIdentity3")>
    UserMappedToExternalIdentity
    <EventCode("U011","EventCodeAttribute_TheUser0ChangedTheExternalIdentityMappingOfUser1From4To3")>
    ChangeExternalIdentity
    <EventCode("U012","EventCodeAttribute_TheUser0UnmappedTheExternalIdentity4FromUser1")>
    DeleteExternalIdentity
    <EventCode("U013","EventCodeAttribute_TheUser0MappedTheUser1ToAnActiveDirectoryUserWithTheFollowingSID2")>
    UserMappedToActiveDirectoryUser
    <EventCode("U014","EventCodeAttribute_TheUser0UnmappedTheUser1FromAnActiveDirectoryUserWithTheFollowingSID2")>
    DeleteMappedActiveDirectoryUser
    <EventCode("U015","EventCodeAttribute_TheUser0ChangedTheActiveDirectoryIdentityMappingOfUser1From4To3")>
    ChangeActiveDirectoryIdentity
    <EventCode("U016",
               "EventCodeAttribute_TheUser0ConvertedTheAccountOfUser1FromSingleAuthSSOToMultiAuthAdSso")>
    UserConvertedToMultiAuthAd
    <EventCode("U017",
               "EventCodeAttribute_TheUser0ConvertedTheAccountOfUser1FromSingleAuthSSOToMultiAuthAdSsoAndMarkedItAsDeleted")>
    UserConvertedToDeletedMultiAuthAd
    <EventCode("U018",
               "EventCodeAttribute_TheUser0MappedTheMultiAuthSsoUser1Roles")>
    UserMappedToMultiAuthAdRoles
    <EventCode("U019",
               "EventCodeAttribute_TheUser0ChangedUser1AuthTypeTo7")>
    UserAuthTypeChanged
    <EventCode("U020",
               "EventCodeAttribute_TheUser0MappedUser1ToAuthenticationServerUserId2")>
    UserMappedToAuthenticationServerUserId
    <EventCode("U021",
               "EventCodeAttribute_TheUser0StartedAnAuthenticationServerMappingFor1Users")>
    AuthenticationServerUserMappingStarted
    <EventCode("U022",
               "EventCodeAttribute_AnAuthenticationServerMappingStartedByUser0Finished")>
    AuthenticationServerUserMappingFinished
    <EventCode("U023",
               "EventCodeAttribute_TheUser0MappedUser1ToAuthenticationServerServiceAccount2")>
    UserMappedToAuthenticationServerServiceAccount
    <EventCode("U024", "EventCodeAttribute_TheUser0ChangedTheHasBluePrismApiPermissionFlagOfTheUser1From3To2")>
    UserHasBluePrismApiScopeChanged
    <EventCode("U025","EventCodeAttribute_TheUser0RestoredTheUser1")>
    RestoreUser
End Enum
