Imports BluePrism.Server.Domain.Models.Attributes

Public Enum WorkQueueItemSortByProperty
    <ColumnNameSortBy(ColumnName:="attempt", SortDirection:="asc") >
    AttemptAsc = 0
    <ColumnNameSortBy(ColumnName:="attempt", SortDirection:="desc") >
    AttemptDesc = 1
    <ColumnNameSortBy(ColumnName:="attemptworktime", SortDirection:="asc") >
    AttemptWorkTimeAsc = 2
    <ColumnNameSortBy(ColumnName:="attemptworktime", SortDirection:="desc") >
    AttemptWorkTimeDesc = 3
    <ColumnNameSortBy(ColumnName:="completed", SortDirection:="asc") >
    CompletedAsc = 4
    <ColumnNameSortBy(ColumnName:="completed", SortDirection:="desc") >
    CompletedDesc = 5
    <ColumnNameSortBy(ColumnName:="deferred", SortDirection:="asc") >
    DeferredAsc = 6
    <ColumnNameSortBy(ColumnName:="deferred", SortDirection:="desc") >
    DeferredDesc = 7
    <ColumnNameSortBy(ColumnName:="exception", SortDirection:="asc") >
    ExceptionAsc = 8
    <ColumnNameSortBy(ColumnName:="exception", SortDirection:="desc") >
    ExceptionDesc = 9
    <ColumnNameSortBy(ColumnName:="exceptionreason", SortDirection:="asc") >
    ExceptionReasonAsc = 10
    <ColumnNameSortBy(ColumnName:="exceptionreason", SortDirection:="desc") >
    ExceptionReasonDesc = 11
    <ColumnNameSortBy(ColumnName:="keyvalue", SortDirection:="asc") >
    KeyValueAsc = 12
    <ColumnNameSortBy(ColumnName:="keyvalue", SortDirection:="desc") >
    KeyValueDesc = 13
    <ColumnNameSortBy(ColumnName:="lastupdated", SortDirection:="asc") >
    LastUpdatedAsc = 14
    <ColumnNameSortBy(ColumnName:="lastupdated", SortDirection:="desc") >
    LastUpdatedDesc = 15
    <ColumnNameSortBy(ColumnName:="loaded", SortDirection:="asc") >
    LoadedAsc = 16
    <ColumnNameSortBy(ColumnName:="loaded", SortDirection:="desc") >
    LoadedDesc = 17
    <ColumnNameSortBy(ColumnName:="locked", SortDirection:="asc") >
    LockedAsc = 18
    <ColumnNameSortBy(ColumnName:="locked", SortDirection:="desc") >
    LockedDesc = 19
    <ColumnNameSortBy(ColumnName:="priority", SortDirection:="asc") >
    PriorityAsc = 20
    <ColumnNameSortBy(ColumnName:="priority", SortDirection:="desc") >
    PriorityDesc = 21
    <ColumnNameSortBy(ColumnName:="status", SortDirection:="asc") >
    StatusAsc = 22
    <ColumnNameSortBy(ColumnName:="status", SortDirection:="desc") >
    StatusDesc = 23
    <ColumnNameSortBy(ColumnName:="worktime", SortDirection:="asc") >
    WorkTimeAsc = 24
    <ColumnNameSortBy(ColumnName:="worktime", SortDirection:="desc") >
    WorkTimeDesc = 25
End Enum
