Imports BluePrism.Scheduling
Imports BluePrism.AutomateAppCore

''' Project  : Automate
''' Class    : IIntervalControl
''' 
''' <summary>
''' Provides a common interface for all the interval controls
''' </summary>
Friend Interface IIntervalControl : Inherits IScheduleModifier

    ''' <summary>
    ''' The actual control object that this interval control uses to display
    ''' itself. In most cases this would be the interval control implementation
    ''' itself.
    ''' </summary>
    ReadOnly Property Control() As Control

    ''' <summary>
    ''' Checks if this control supports the given interval or not.
    ''' </summary>
    ''' <param name="interval">The interval to check if the control supports it
    ''' or not.</param>
    ''' <returns>True if this control supports the given interval type, false
    ''' otherwise.</returns>
    Function SupportsInterval(ByVal interval As IntervalType) As Boolean

    ''' <summary>
    ''' Gets the TriggerMetaData generated by the fields on the control.
    ''' This may be empty if the control has no fields which affect the trigger
    ''' metadata. It will only return a null value if there are validation errors
    ''' on the control - if this is the case, and appopriate error will be placed
    ''' in the specified collection.
    ''' </summary>
    ''' <param name="err">The collection into which any validation errors will
    ''' be placed if any are found in the control</param>
    ''' <returns>The trigger meta data which represents the data held on this 
    ''' control, or null if any validation errors occurred on this control.
    ''' </returns>
    Function GetData(ByVal err As ICollection(Of clsValidationError)) As TriggerMetaData

    ''' <summary>
    ''' Populates the control from the given TriggerMetaData
    ''' </summary>
    ''' <param name="data">The TriggerMetaData to populate the control with
    ''' </param>
    ''' <param name="sched">The schedule also needed to populate some controls
    ''' </param>
    Sub Populate(ByVal data As TriggerMetaData, ByVal sched As SessionRunnerSchedule)

    ''' <summary>
    ''' Sets the start date needed by some controls
    ''' </summary>
    ''' <param name="d">The Date</param>
    Sub SetStartDate(ByVal d As Date)

    ''' <summary>
    ''' Gets or sets the readonly state of this control - a readonly control is
    ''' typically not editable, but its interface is functional enough to allow
    ''' the value to be copied, or the contents to be navigated by the user (eg.
    ''' scrolling a table / list, etc).
    ''' </summary>
    Property [ReadOnly]() As Boolean

End Interface
