namespace BluePrism.Api.Models
{
    public enum WorkQueueItemSortBy
    {
        AttemptAsc, 
        AttemptDesc,
        AttemptWorkTimeAsc,
        AttemptWorkTimeDesc,
        CompletedAsc,
        CompletedDesc,
        DeferredAsc,
        DeferredDesc,
        ExceptionAsc,
        ExceptionDesc,
        ExceptionReasonAsc,
        ExceptionReasonDesc,
        KeyValueAsc,
        KeyValueDesc,
        LastUpdatedAsc,
        LastUpdatedDesc,
        LoadedAsc,
        LoadedDesc,
        LockedAsc,
        LockedDesc,
        PriorityAsc,
        PriorityDesc,
        StatusAsc,
        StatusDesc,
        WorkTimeAsc,
        WorkTimeDesc,
    }
}
