'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class RobotImages
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AutomateUI.RobotImages", GetType(RobotImages).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Custom_Resource_Connecting_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Custom_Resource_Connecting_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Custom_Resource_Error_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Custom_Resource_Error_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Custom_Resource_LoginAgent_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Custom_Resource_LoginAgent_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Custom_Resource_Offline_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Custom_Resource_Offline_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Custom_Resource_Online_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Custom_Resource_Online_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Custom_Resource_Unavailable_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Custom_Resource_Unavailable_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Custom_Resource_Warning_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Custom_Resource_Warning_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Custom_Resource_Working_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Custom_Resource_Working_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_16x16_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_16x16_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_16x16_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_16x16_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_32x32_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_32x32_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_32x32_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_32x32_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Delete_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Delete_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Delete_16x16_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Delete_16x16_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Delete_16x16_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Delete_16x16_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Delete_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Delete_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Delete_32x32_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Delete_32x32_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Delete_32x32_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Delete_32x32_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Error_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Error_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Error_16x16_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Error_16x16_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Error_16x16_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Error_16x16_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Error_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Error_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Error_32x32_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Error_32x32_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Error_32x32_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Error_32x32_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Information_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Information_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Information_16x16_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Information_16x16_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Information_16x16_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Information_16x16_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Information_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Information_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Information_32x32_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Information_32x32_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Information_32x32_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Information_32x32_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Internet_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Internet_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Internet_16x16_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Internet_16x16_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Internet_16x16_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Internet_16x16_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Internet_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Internet_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Internet_32x32_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Internet_32x32_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Internet_32x32_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Internet_32x32_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Lock_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Lock_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Lock_16x16_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Lock_16x16_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Lock_16x16_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Lock_16x16_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Lock_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Lock_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Lock_32x32_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Lock_32x32_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Lock_32x32_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Lock_32x32_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_New_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_New_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_New_16x16_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_New_16x16_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_New_16x16_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_New_16x16_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_New_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_New_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_New_32x32_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_New_32x32_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_New_32x32_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_New_32x32_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Share_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Share_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Share_16x16_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Share_16x16_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Share_16x16_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Share_16x16_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Share_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Share_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Share_32x32_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Share_32x32_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Share_32x32_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Share_32x32_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Tick_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Tick_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Tick_16x16_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Tick_16x16_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Tick_16x16_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Tick_16x16_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Tick_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Tick_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Tick_32x32_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Tick_32x32_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Tick_32x32_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Tick_32x32_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Warning_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Warning_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Warning_16x16_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Warning_16x16_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Warning_16x16_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Warning_16x16_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Warning_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Warning_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Warning_32x32_Disabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Warning_32x32_Disabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PC_Warning_32x32_Hot() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PC_Warning_32x32_Hot", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
