'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Controls.Widgets.SystemManager.WebApi
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class WebApi_Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AutomateUI.WebApi.Resources", GetType(WebApi_Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This action name already exists in the Web API. Note, that all non alpha-numeric characters will be treated as underscores when comparing names..
        '''</summary>
        Friend Shared ReadOnly Property ActionNameExistsMessage_Template() As String
            Get
                Return ResourceManager.GetString("ActionNameExistsMessage_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actions.
        '''</summary>
        Friend Shared ReadOnly Property ActionsNode() As String
            Get
                Return ResourceManager.GetString("ActionsNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compilation failed:
        '''{0}.
        '''</summary>
        Friend Shared ReadOnly Property CodeValidation_ErrorsFoundMessageTemplate() As String
            Get
                Return ResourceManager.GetString("CodeValidation_ErrorsFoundMessageTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General error: {0}.
        '''</summary>
        Friend Shared ReadOnly Property CodeValidation_GeneralCodeCompilerErrorTemplate() As String
            Get
                Return ResourceManager.GetString("CodeValidation_GeneralCodeCompilerErrorTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Action &quot;{0}&quot; (line {1}): {2}.
        '''</summary>
        Friend Shared ReadOnly Property CodeValidation_RequestContentCodeCompilerErrorTemplate() As String
            Get
                Return ResourceManager.GetString("CodeValidation_RequestContentCodeCompilerErrorTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shared code (line {0}): {1}.
        '''</summary>
        Friend Shared ReadOnly Property CodeValidation_SharedCodeCompilerErrorTemplate() As String
            Get
                Return ResourceManager.GetString("CodeValidation_SharedCodeCompilerErrorTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code compiled successfully..
        '''</summary>
        Friend Shared ReadOnly Property CodeValidation_SuccessMessage() As String
            Get
                Return ResourceManager.GetString("CodeValidation_SuccessMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Common Authentication.
        '''</summary>
        Friend Shared ReadOnly Property CommonAuthenticationsNode() As String
            Get
                Return ResourceManager.GetString("CommonAuthenticationsNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Common Code.
        '''</summary>
        Friend Shared ReadOnly Property CommonCode() As String
            Get
                Return ResourceManager.GetString("CommonCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to populate field with selection - there is no active row. Please select a row by placing the cursor in it before browsing for an external resource..
        '''</summary>
        Friend Shared ReadOnly Property CommonCode_Unable_To_Populate_Field() As String
            Get
                Return ResourceManager.GetString("CommonCode_Unable_To_Populate_Field", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Common Headers.
        '''</summary>
        Friend Shared ReadOnly Property CommonHeadersNode() As String
            Get
                Return ResourceManager.GetString("CommonHeadersNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Common Parameters.
        '''</summary>
        Friend Shared ReadOnly Property CommonParametersNode() As String
            Get
                Return ResourceManager.GetString("CommonParametersNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to restore the default settings?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmationText_RestoreDefaultConfigSettings() As String
            Get
                Return ResourceManager.GetString("ConfirmationText_RestoreDefaultConfigSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not commit changes to current selection: {0}.
        '''</summary>
        Friend Shared ReadOnly Property CouldNotCommitChanges_Template() As String
            Get
                Return ResourceManager.GetString("CouldNotCommitChanges_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete the action &apos;{0}&apos;?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteActionPrompt_Template() As String
            Get
                Return ResourceManager.GetString("DeleteActionPrompt_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter new parameter.
        '''</summary>
        Friend Shared ReadOnly Property EnterNewParameter() As String
            Get
                Return ResourceManager.GetString("EnterNewParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Action name cannot be empty..
        '''</summary>
        Friend Shared ReadOnly Property ErrorActionNameCannotBeEmpty() As String
            Get
                Return ResourceManager.GetString("ErrorActionNameCannotBeEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Authorization URI cannot be empty.
        '''</summary>
        Friend Shared ReadOnly Property ErrorAuthUrlCannotBeEmpty() As String
            Get
                Return ResourceManager.GetString("ErrorAuthUrlCannotBeEmpty", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The Base URL of a Web API cannot be empty.
        '''</summary>
        Friend Shared ReadOnly Property ErrorBaseUrlCannotBeEmpty() As String
            Get
                Return ResourceManager.GetString("ErrorBaseUrlCannotBeEmpty", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The Base URL of a Web API cannot be empty.
        '''</summary>
        Friend Shared ReadOnly Property UrlWhitespaceWarning() As String
            Get
                Return ResourceManager.GetString("UrlWhitespaceWarning", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to An error occurred while compiling the Web API: {0}.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCreatingWebApi_Template() As String
            Get
                Return ResourceManager.GetString("ErrorCreatingWebApi_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An action with the name &apos;{0}&apos; already exists.
        '''</summary>
        Friend Shared ReadOnly Property ErrorDuplicateActionName_Template() As String
            Get
                Return ResourceManager.GetString("ErrorDuplicateActionName_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicate header found on row {0}.
        '''</summary>
        Friend Shared ReadOnly Property ErrorDuplicateHeader_Template() As String
            Get
                Return ResourceManager.GetString("ErrorDuplicateHeader_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicate parameter found on row {0}.  Note, that all non alpha-numeric characters will be treated as underscores when comparing names..
        '''</summary>
        Friend Shared ReadOnly Property ErrorDuplicateParameter_Template() As String
            Get
                Return ResourceManager.GetString("ErrorDuplicateParameter_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Web API with the name &apos;{0}&apos; already exists.
        '''</summary>
        Friend Shared ReadOnly Property ErrorDuplicateWebApiName_Template() As String
            Get
                Return ResourceManager.GetString("ErrorDuplicateWebApiName_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter Name must not be empty when Expose to Process is set to True.
        '''</summary>
        Friend Shared ReadOnly Property ErrorEmptyAuthParameterName() As String
            Get
                Return ResourceManager.GetString("ErrorEmptyAuthParameterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter name cannot be empty.
        '''</summary>
        Friend Shared ReadOnly Property ErrorEmptyParameter() As String
            Get
                Return ResourceManager.GetString("ErrorEmptyParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Web API name must not be empty.
        '''</summary>
        Friend Shared ReadOnly Property ErrorEmptyWebApiName() As String
            Get
                Return ResourceManager.GetString("ErrorEmptyWebApiName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to populate Credentials List: {0}.
        '''</summary>
        Friend Shared ReadOnly Property ErrorFailedToPopulateCredentialsList_Template() As String
            Get
                Return ResourceManager.GetString("ErrorFailedToPopulateCredentialsList_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Authentication URL &apos;{0}&apos; is invalid: {1}.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInvalidAuthenticationUrl_Template() As String
            Get
                Return ResourceManager.GetString("ErrorInvalidAuthenticationUrl_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Base URL &apos;{0}&apos; is invalid: {1}.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInvalidBaseUrl_Template() As String
            Get
                Return ResourceManager.GetString("ErrorInvalidBaseUrl_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data type is invalid.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInvalidDataType() As String
            Get
                Return ResourceManager.GetString("ErrorInvalidDataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter name cannot contain a full-stop.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInvalidParameterName() As String
            Get
                Return ResourceManager.GetString("ErrorInvalidParameterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter type is invalid.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInvalidParameterType() As String
            Get
                Return ResourceManager.GetString("ErrorInvalidParameterType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Path is not a valid JSON path.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInvalidPath() As String
            Get
                Return ResourceManager.GetString("ErrorInvalidPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Request timeout values must be whole numbers between 1 and 100000..
        '''</summary>
        Friend Shared ReadOnly Property ErrorInvalidRequestTimoutValue() As String
            Get
                Return ResourceManager.GetString("ErrorInvalidRequestTimoutValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The given URL was not valid: {0}.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInvalidUrl_Template() As String
            Get
                Return ResourceManager.GetString("ErrorInvalidUrl_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Root element ($) missing from start of path..
        '''</summary>
        Friend Shared ReadOnly Property ErrorRootElementTokenMissingFromPath() As String
            Get
                Return ResourceManager.GetString("ErrorRootElementTokenMissingFromPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while validating the Web API.
        '''</summary>
        Friend Shared ReadOnly Property ErrorValidatingWebApi() As String
            Get
                Return ResourceManager.GetString("ErrorValidatingWebApi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while validating response output parameters: {0}.
        '''</summary>
        Friend Shared ReadOnly Property ErrorValidatingWebApiCustomOutputParameters_Template() As String
            Get
                Return ResourceManager.GetString("ErrorValidatingWebApiCustomOutputParameters_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while validating parameters: {0}.
        '''</summary>
        Friend Shared ReadOnly Property ErrorValidatingWebApiCustomParameters_Template() As String
            Get
                Return ResourceManager.GetString("ErrorValidatingWebApiCustomParameters_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to External References.
        '''</summary>
        Friend Shared ReadOnly Property ExternalReferences() As String
            Get
                Return ResourceManager.GetString("ExternalReferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complete the settings to define the action. Only enabled actions can be called from Objects and Processes. Values of Common Parameters and action-specific Parameters can be used dynamically in the URL Path and request Body when specified in the format [parameter name]..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceActionPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceActionPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configure the request for this API definition by selecting a method and adding a URL path and request body..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceActionRequestPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceActionRequestPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configure the response for the API action by creating additional custom output parameters. The output parameter values are derived from the HTTP response body, and each output parameter value can be generated either by defining a path to the value within a JSON response or by providing custom code to calculate the value..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceActionResponsePanel() As String
            Get
                Return ResourceManager.GetString("GuidanceActionResponsePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configure headers, specific to this action, that are used in addition to the common headers for this API definition. The value can contain common parameters and actions specific parameters when specified in the format [parameter name]. If a common header and action-specific header have the same name, the value of the action-specific header is used when the API is called..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceActionSpecificHttpHeaderPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceActionSpecificHttpHeaderPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configure parameters, specific to this action, that are available in addition to the common parameters for this definition. Parameter values can be used dynamically in URL paths, header values, and request bodies when specified in the format [parameter name]. Parameter names must be unique within the API definition..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceActionSpecificParametersPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceActionSpecificParametersPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click Add Action to create and configure a new action for this API definition. The actions are available when the Web API Service is included in an Object or Process..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceActionSummary() As String
            Get
                Return ResourceManager.GetString("GuidanceActionSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use HTTP Basic Authentication to send the username and password from the selected credential in API requests. Select &apos;Expose to process&apos; to make the credential available as an input for actions, listed under the entered Parameter Name..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceBasicAuthenticationPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceBasicAuthenticationPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set up bearer token authentication where the bearer token has already been retreived and stored in a credential. Bearer tokens are most widely used with OAuth 2.0 authentication and JWT authentication..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceBearerTokenAuthenticationPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceBearerTokenAuthenticationPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specify the language, settings and shared functionality used by custom code within this Web API.
        '''</summary>
        Friend Shared ReadOnly Property GuidanceCommonCodePanel() As String
            Get
                Return ResourceManager.GetString("GuidanceCommonCodePanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This authentication type allows a custom authentication to be set up using the selected credential&apos;s properties as parameters when building the configured request. It is recommended to select a General credential for this authentication type. Username can be accessed using the syntax [Credential.Username], password using[Credential.Password] and any specified credential properties using [Credential.AdditionalProperties.&lt;propertyName&gt;]..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceCustomAuthenticationPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceCustomAuthenticationPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a unique name and the Base URL of the Web API. The URL is used in all requests generated by the actions within this definition. The Base URL can contain Common Parameter values when specified in the format [parameter name]..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceDetailPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceDetailPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select and configure an authentication type for the actions in this API definition..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceEmptyAuthenticationPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceEmptyAuthenticationPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configure headers that are used in all actions for this API definition. The Header Value can contain Common Parameters values when specified in the format [parameter name]..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceHttpHeaderPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceHttpHeaderPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This authentication type uses a client identifier and client secret stored in a credential to retrieve an OAuth 2.0 access token from an authorization server. The access token is then used to authenticate Web API requests..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceOAuth2AuthenticationPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceOAuth2AuthenticationPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This authentication type generates a JWT Bearer Token that is used to retrieve an OAuth 2.0 access token from an authorization server. The access token is then used to authenticate Web API requests..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceOAuth2WithJwtAuthenticationPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceOAuth2WithJwtAuthenticationPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configure parameters available for all actions. Parameter values can be used dynamically in URL Paths, Header Values and request bodies when specified in the format [parameter name]..
        '''</summary>
        Friend Shared ReadOnly Property GuidanceParametersPanel() As String
            Get
                Return ResourceManager.GetString("GuidanceParametersPanel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Headers.
        '''</summary>
        Friend Shared ReadOnly Property HeadersNode() As String
            Get
                Return ResourceManager.GetString("HeadersNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Namespace Imports.
        '''</summary>
        Friend Shared ReadOnly Property NamespaceImports() As String
            Get
                Return ResourceManager.GetString("NamespaceImports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Action {0}.
        '''</summary>
        Friend Shared ReadOnly Property NewActionName_Template() As String
            Get
                Return ResourceManager.GetString("NewActionName_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Web API Service {0}.
        '''</summary>
        Friend Shared ReadOnly Property NewWebApiName_Template() As String
            Get
                Return ResourceManager.GetString("NewWebApiName_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameters.
        '''</summary>
        Friend Shared ReadOnly Property ParametersNode() As String
            Get
                Return ResourceManager.GetString("ParametersNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove parameter.
        '''</summary>
        Friend Shared ReadOnly Property RemoveParameter() As String
            Get
                Return ResourceManager.GetString("RemoveParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Request.
        '''</summary>
        Friend Shared ReadOnly Property RequestNode() As String
            Get
                Return ResourceManager.GetString("RequestNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Response.
        '''</summary>
        Friend Shared ReadOnly Property ResponseNode() As String
            Get
                Return ResourceManager.GetString("ResponseNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The time before the authorization server request will timeout..
        '''</summary>
        Friend Shared ReadOnly Property ToolTip_AuthServerRequestTimeoutConfigSetting() As String
            Get
                Return ResourceManager.GetString("ToolTip_AuthServerRequestTimeoutConfigSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The time before the request will timeout..
        '''</summary>
        Friend Shared ReadOnly Property ToolTip_HttpRequestTimeoutConfigSetting() As String
            Get
                Return ResourceManager.GetString("ToolTip_HttpRequestTimeoutConfigSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Web API is associated with a Skill..
        '''</summary>
        Friend Shared ReadOnly Property WarningLinkedToSkill() As String
            Get
                Return ResourceManager.GetString("WarningLinkedToSkill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Web API: {0}.
        '''</summary>
        Friend Shared ReadOnly Property WindowTitle_Template() As String
            Get
                Return ResourceManager.GetString("WindowTitle_Template", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
