'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace WebApis
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class WebApiResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BluePrism.AutomateProcessCore.WebApiResources", GetType(WebApiResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Basic.
        '''</summary>
        Public Shared ReadOnly Property AuthenticationType_Basic() As String
            Get
                Return ResourceManager.GetString("AuthenticationType_Basic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bearer Token.
        '''</summary>
        Public Shared ReadOnly Property AuthenticationType_BearerToken() As String
            Get
                Return ResourceManager.GetString("AuthenticationType_BearerToken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom.
        '''</summary>
        Public Shared ReadOnly Property AuthenticationType_Custom() As String
            Get
                Return ResourceManager.GetString("AuthenticationType_Custom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Public Shared ReadOnly Property AuthenticationType_None() As String
            Get
                Return ResourceManager.GetString("AuthenticationType_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OAuth 2.0 (Client Credentials).
        '''</summary>
        Public Shared ReadOnly Property AuthenticationType_OAuth2ClientCredentials() As String
            Get
                Return ResourceManager.GetString("AuthenticationType_OAuth2ClientCredentials", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OAuth 2.0 (JWT Bearer Token).
        '''</summary>
        Public Shared ReadOnly Property AuthenticationType_OAuth2JwtBearerToken() As String
            Get
                Return ResourceManager.GetString("AuthenticationType_OAuth2JwtBearerToken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A credential authentication has not been chosen in the Web API configuration..
        '''</summary>
        Public Shared ReadOnly Property CredentialNotSelectedError() As String
            Get
                Return ResourceManager.GetString("CredentialNotSelectedError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credential name input parameter &quot;{0}&quot; is missing or empty and a credential has not been chosen in the Web API configuration..
        '''</summary>
        Public Shared ReadOnly Property CredentialParameterMissingErrorTemplate() As String
            Get
                Return ResourceManager.GetString("CredentialParameterMissingErrorTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot execute action &quot;{0}&quot; due to an error when running custom code: {1}.
        '''</summary>
        Public Shared ReadOnly Property CustomCodeExecutionErrorTemplate() As String
            Get
                Return ResourceManager.GetString("CustomCodeExecutionErrorTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code used to generate content in action {0}.
        '''</summary>
        Public Shared ReadOnly Property CustomCodeLocationTitleTemplate() As String
            Get
                Return ResourceManager.GetString("CustomCodeLocationTitleTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot execute action &quot;{0}&quot; because an error occurred while compiling custom code. Errors were found in the following locations:
        '''{1}.
        '''</summary>
        Public Shared ReadOnly Property CustomCodeRunTimeCompilationErrorTemplate() As String
            Get
                Return ResourceManager.GetString("CustomCodeRunTimeCompilationErrorTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Type mismatch in array: Element &apos;{0}&apos; has type instead of expected type &apos;{1}&apos;.
        '''</summary>
        Public Shared ReadOnly Property DataMismatchTemplate() As String
            Get
                Return ResourceManager.GetString("DataMismatchTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Web API action contains output parameters based on JSON data, but the response does not contain valid JSON content..
        '''</summary>
        Public Shared ReadOnly Property ErrorParsingJson() As String
            Get
                Return ResourceManager.GetString("ErrorParsingJson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The media type of the content..
        '''</summary>
        Public Shared ReadOnly Property FileCollectionBodyContent_InputCollection_Fields_ContentType_Description() As String
            Get
                Return ResourceManager.GetString("FileCollectionBodyContent_InputCollection_Fields_ContentType_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The HTML field in the form that the content refers to..
        '''</summary>
        Public Shared ReadOnly Property FileCollectionBodyContent_InputCollection_Fields_FieldName_Description() As String
            Get
                Return ResourceManager.GetString("FileCollectionBodyContent_InputCollection_Fields_FieldName_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The binary content being transmitted..
        '''</summary>
        Public Shared ReadOnly Property FileCollectionBodyContent_InputCollection_Fields_File_Description() As String
            Get
                Return ResourceManager.GetString("FileCollectionBodyContent_InputCollection_Fields_File_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The original file name of the content being transmitted..
        '''</summary>
        Public Shared ReadOnly Property FileCollectionBodyContent_InputCollection_Fields_FileName_Description() As String
            Get
                Return ResourceManager.GetString("FileCollectionBodyContent_InputCollection_Fields_FileName_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file collection to send in the Web API Request.
        '''</summary>
        Public Shared ReadOnly Property FileCollectionInputParameterDescription() As String
            Get
                Return ResourceManager.GetString("FileCollectionInputParameterDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to get OAuth2.0 Access Token : &quot;{0}&quot; &quot;{1}&quot;.
        '''</summary>
        Public Shared ReadOnly Property OAuth2AccessTokenExceptionTemplate() As String
            Get
                Return ResourceManager.GetString("OAuth2AccessTokenExceptionTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to get OAuth2.0 Access Token: Invalid token.
        '''</summary>
        Public Shared ReadOnly Property OAuth2InvalidTokenException() As String
            Get
                Return ResourceManager.GetString("OAuth2InvalidTokenException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom Code.
        '''</summary>
        Public Shared ReadOnly Property RequestBodyType_CustomCode_Title() As String
            Get
                Return ResourceManager.GetString("RequestBodyType_CustomCode_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Files.
        '''</summary>
        Public Shared ReadOnly Property RequestBodyType_MultiFile_ParameterName() As String
            Get
                Return ResourceManager.GetString("RequestBodyType_MultiFile_ParameterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multiple Files.
        '''</summary>
        Public Shared ReadOnly Property RequestBodyType_MultiFile_Title() As String
            Get
                Return ResourceManager.GetString("RequestBodyType_MultiFile_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Public Shared ReadOnly Property RequestBodyType_None_Title() As String
            Get
                Return ResourceManager.GetString("RequestBodyType_None_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File.
        '''</summary>
        Public Shared ReadOnly Property RequestBodyType_SingleFile_ParameterName() As String
            Get
                Return ResourceManager.GetString("RequestBodyType_SingleFile_ParameterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Single File.
        '''</summary>
        Public Shared ReadOnly Property RequestBodyType_SingleFile_Title() As String
            Get
                Return ResourceManager.GetString("RequestBodyType_SingleFile_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Template.
        '''</summary>
        Public Shared ReadOnly Property RequestBodyType_Template_Title() As String
            Get
                Return ResourceManager.GetString("RequestBodyType_Template_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom Code.
        '''</summary>
        Public Shared ReadOnly Property ResponseOutputParameterType_CustomCode_Title() As String
            Get
                Return ResourceManager.GetString("ResponseOutputParameterType_CustomCode_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Json Path.
        '''</summary>
        Public Shared ReadOnly Property ResponseOutputParameterType_JsonPath_Title() As String
            Get
                Return ResourceManager.GetString("ResponseOutputParameterType_JsonPath_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Public Shared ReadOnly Property ResponseOutputParameterType_None_Title() As String
            Get
                Return ResourceManager.GetString("ResponseOutputParameterType_None_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The header &quot;{0}&quot; cannot be set manually.
        '''</summary>
        Public Shared ReadOnly Property RestrictedHeaderNotSupportedErrorTemplate() As String
            Get
                Return ResourceManager.GetString("RestrictedHeaderNotSupportedErrorTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shared code.
        '''</summary>
        Public Shared ReadOnly Property SharedCodeLocationTitle() As String
            Get
                Return ResourceManager.GetString("SharedCodeLocationTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file to send in the Web API Request.
        '''</summary>
        Public Shared ReadOnly Property SingleFileInputParameterDescription() As String
            Get
                Return ResourceManager.GetString("SingleFileInputParameterDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unrecognised action &quot;{0}&quot;.
        '''</summary>
        Public Shared ReadOnly Property UnknownActionErrorTemplate() As String
            Get
                Return ResourceManager.GetString("UnknownActionErrorTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unrecognised credential &quot;{0}&quot;.
        '''</summary>
        Public Shared ReadOnly Property UnknownCredentialErrorTemplate() As String
            Get
                Return ResourceManager.GetString("UnknownCredentialErrorTemplate", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
