'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AutomateUI_Controls
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AutomateUI.AutomateUI.Controls", GetType(AutomateUI_Controls).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You do not have permission to access this part of the system. If you believe that this is incorrect then please contact your {0} administrator..
        '''</summary>
        Friend Shared ReadOnly Property ctlDevelopView_CheckPermission_YouDoNotHavePermissionToAccess() As String
            Get
                Return ResourceManager.GetString("ctlDevelopView_CheckPermission_YouDoNotHavePermissionToAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This package contains items which you do not have access to. If you modify it, these items will be removed from the package and you will be unable to add them again.
        '''Are you sure you wish to continue?.
        '''</summary>
        Friend Shared ReadOnly Property ctlPackageDetails_HandleEditPackageClicked_WarningMessage() As String
            Get
                Return ResourceManager.GetString("ctlPackageDetails_HandleEditPackageClicked_WarningMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This package contains items which you do not have access to. If you modify it, these items will be removed from the package..
        '''</summary>
        Friend Shared ReadOnly Property ctlPackageDetails_Package_InaccessibleItemsWarning() As String
            Get
                Return ResourceManager.GetString("ctlPackageDetails_Package_InaccessibleItemsWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This {0} cannot be saved because you do not have permission to execute all linked processes or business objects. Please either remove the affected links or contact your administrator to obtain permission..
        '''</summary>
        Friend Shared ReadOnly Property ctlProcessViewer_CannotBeSavedPermissionToExecuteAllLinked() As String
            Get
                Return ResourceManager.GetString("ctlProcessViewer_CannotBeSavedPermissionToExecuteAllLinked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The {0} &apos;{1}&apos; cannot be saved because you do not have permission to execute all linked processes or business objects. Closing at this time will cause all changes to be lost, do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property ctlProcessViewer_CannotBeSavedPermissionToExecuteAllLinkedOnClose() As String
            Get
                Return ResourceManager.GetString("ctlProcessViewer_CannotBeSavedPermissionToExecuteAllLinkedOnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This operation can not be performed until you have saved the {0}; please save the {0} first..
        '''</summary>
        Friend Shared ReadOnly Property ctlProcessViewer_DebugAction_OperationCanNotBePerformedUntilSave() As String
            Get
                Return ResourceManager.GetString("ctlProcessViewer_DebugAction_OperationCanNotBePerformedUntilSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to business object.
        '''</summary>
        Friend Shared ReadOnly Property ctlProcessViewer_GetOpenObjectType_BusinessObject() As String
            Get
                Return ResourceManager.GetString("ctlProcessViewer_GetOpenObjectType_BusinessObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to process.
        '''</summary>
        Friend Shared ReadOnly Property ctlProcessViewer_GetOpenObjectType_Process() As String
            Get
                Return ResourceManager.GetString("ctlProcessViewer_GetOpenObjectType_Process", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   You cannot edit the {0} while it is locked. Would you like to view this {0} instead?.
        '''</summary>
        Friend Shared ReadOnly Property ctlProcessViewer_Startup_CannotEditWhileLockedViewInstead() As String
            Get
                Return ResourceManager.GetString("ctlProcessViewer_Startup_CannotEditWhileLockedViewInstead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This {0} cannot be saved because it contains references to some processes or business objects that are not available..
        '''</summary>
        Friend Shared ReadOnly Property ctlProcessViewer_Startup_ContainsReferencesThatAreNotAvailable() As String
            Get
                Return ResourceManager.GetString("ctlProcessViewer_Startup_ContainsReferencesThatAreNotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your lock on this {0} has been removed by another user. Please either quit, or use Save As to create a new {0}..
        '''</summary>
        Friend Shared ReadOnly Property ctlProcessViewer_UserHasLock_LockRemovedByAnotherUser() As String
            Get
                Return ResourceManager.GetString("ctlProcessViewer_UserHasLock_LockRemovedByAnotherUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you delete this item you will be unable to add it again as you don&apos;t have the required permissions to interact with it. Are you sure you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property ctlTask_HandleDeleteSessionClicked_WarningMessage() As String
            Get
                Return ResourceManager.GetString("ctlTask_HandleDeleteSessionClicked_WarningMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If removed, this session cannot be re-added as you do not have permissions to interact with it..
        '''</summary>
        Friend Shared ReadOnly Property ctlTask_Task_ProcessNotVisibleToUser() As String
            Get
                Return ResourceManager.GetString("ctlTask_Task_ProcessNotVisibleToUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This object does not have an application model and you do not have permission to edit the object.
        '''</summary>
        Friend Shared ReadOnly Property frmProcess_ShowIntegrationAssistant_ObjectDoesNotHaveApplicationModel() As String
            Get
                Return ResourceManager.GetString("frmProcess_ShowIntegrationAssistant_ObjectDoesNotHaveApplicationModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The shared application model is not available because the parent object ({0}) is not installed..
        '''</summary>
        Friend Shared ReadOnly Property frmProcess_ShowIntegrationAssistant_SharedApplicationModelNotAvailable() As String
            Get
                Return ResourceManager.GetString("frmProcess_ShowIntegrationAssistant_SharedApplicationModelNotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The shared application model is not available because the parent object ({0}) is not installed. Do you want to select a different parent object?.
        '''</summary>
        Friend Shared ReadOnly Property frmProcess_ShowIntegrationAssistant_SharedApplicationModelNotAvailableParent() As String
            Get
                Return ResourceManager.GetString("frmProcess_ShowIntegrationAssistant_SharedApplicationModelNotAvailableParent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ⚠.
        '''</summary>
        Friend Shared ReadOnly Property General_WarningSymbol() As String
            Get
                Return ResourceManager.GetString("General_WarningSymbol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show all unrestricted groups.
        '''</summary>
        Friend Shared ReadOnly Property ShowAllUnrestrictedGroups() As String
            Get
                Return ResourceManager.GetString("ShowAllUnrestrictedGroups", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
