//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrism.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluePrism.Core.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted data {0} doesn&apos;t have expected row identifier {1}.
        /// </summary>
        public static string DatabaseDataEncryption_DecryptedData0DoesnTHaveExpectedRowIdentifier1 {
            get {
                return ResourceManager.GetString("DatabaseDataEncryption_DecryptedData0DoesnTHaveExpectedRowIdentifier1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize an empty string..
        /// </summary>
        public static string GZipCompression_CannotDeserializeEmptyString {
            get {
                return ResourceManager.GetString("GZipCompression_CannotDeserializeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encoding type: {0}.
        /// </summary>
        public static string HttpWebResponseExtensionMethods_InvalidEncodingType0 {
            get {
                return ResourceManager.GetString("HttpWebResponseExtensionMethods_InvalidEncodingType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must specify a simple member access expression.
        /// </summary>
        public static string MemberAccessHelper_ExpressionMustSpecifyASimpleMemberAccessExpression {
            get {
                return ResourceManager.GetString("MemberAccessHelper_ExpressionMustSpecifyASimpleMemberAccessExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must specify a simple member on the target instance. Nested members are not permitted..
        /// </summary>
        public static string MemberAccessHelper_ExpressionMustSpecifyASimpleMemberOnTheTargetInstanceNestedMembersAreNotPermitt {
            get {
                return ResourceManager.GetString("MemberAccessHelper_ExpressionMustSpecifyASimpleMemberOnTheTargetInstanceNestedMem" +
                        "bersAreNotPermitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Server cannot currently communicate with this online resource. ({0}).
        /// </summary>
        public static string OnDemandResourceConnectionCannotConnectToAppServer {
            get {
                return ResourceManager.GetString("OnDemandResourceConnectionCannotConnectToAppServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Server failed to connect to {0} at {1} taking {2}ms to attempt connection.
        /// </summary>
        public static string OnDemandResourceConnectionFailed {
            get {
                return ResourceManager.GetString("OnDemandResourceConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Server connected to {0} at {1} taking {2}ms to connect.
        /// </summary>
        public static string OnDemandResourceConnectionSucceeded {
            get {
                return ResourceManager.GetString("OnDemandResourceConnectionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the resource timed out..
        /// </summary>
        public static string UnableToConnect_ConnectionTimeout {
            get {
                return ResourceManager.GetString("UnableToConnect_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to resource. Possible IPv4 / IPv6 mismatch between client and resource..
        /// </summary>
        public static string UnableToConnect_IPVersionMismatch {
            get {
                return ResourceManager.GetString("UnableToConnect_IPVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to resource. Unable to get IP address for host..
        /// </summary>
        public static string UnableToConnect_NoIPAddress {
            get {
                return ResourceManager.GetString("UnableToConnect_NoIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WCF performance parameter must be a valid numerical value and be between 1 and 1440 minutes..
        /// </summary>
        public static string WCFPerformance_Invalid {
            get {
                return ResourceManager.GetString("WCFPerformance_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; for the XML attribute &apos;{1}&apos; cannot be converted to {2}.
        /// </summary>
        public static string XAttributeExtensionMethods_TheValue0ForTheXMLAttribute1CannotBeConvertedTo2 {
            get {
                return ResourceManager.GetString("XAttributeExtensionMethods_TheValue0ForTheXMLAttribute1CannotBeConvertedTo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; for the XML attribute &apos;{1}&apos; is not a valid URI.
        /// </summary>
        public static string XAttributeExtensionMethods_TheValue0ForTheXMLAttribute1IsNotAValidURI {
            get {
                return ResourceManager.GetString("XAttributeExtensionMethods_TheValue0ForTheXMLAttribute1IsNotAValidURI", resourceCulture);
            }
        }
    }
}
