using NLog;
using System.IO;
using BluePrism.AutomateAppCore;
using BluePrism.BPCoreLib;
using NLog.Config;

namespace BluePrism.AppMan.Logging
{
    /// <summary>
    /// Configures NLog at application startup when running AppMan. Log configuration
    /// is shared with the main Automate application, but a separate application name
    /// is defined which will result in separate text log files being generated by
    /// the standard log configuration.
    /// </summary>
    public static class AppManNLogConfig
    {
        private const string ConfigurationFileName = "Automate.NLog.config";

        /// <summary>
        /// Configures logging based on configuration file. This should be called immediately on
        /// application startup.
        /// </summary>
        public static void Configure()
        {
            var filePath = Path.Combine(clsFileSystem.CommonAppDataDirectory, ConfigurationFileName);
            if (File.Exists(filePath))
            {
                LogManager.Configuration = new XmlLoggingConfiguration(filePath, new LogFactory
                {
                    ThrowConfigExceptions = false
                });
                GlobalDiagnosticsContext.Set("AppName", "ExternalAppMan");
                GlobalDiagnosticsContext.Set("AppEventLogSource", EventLogHelper.DefaultSource);
            }
        }
    }
}
