//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillPackager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SkillPackagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SkillPackagerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkillPackager.SkillPackagerResources", typeof(SkillPackagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to export skill: {0}.
        /// </summary>
        internal static string Error_ExportingSkill_Template {
            get {
                return ResourceManager.GetString("Error_ExportingSkill_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon height is greater than the maximum: {0} px..
        /// </summary>
        internal static string Error_ImageHeightGreaterThanMaximum {
            get {
                return ResourceManager.GetString("Error_ImageHeightGreaterThanMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon width is greater than the maximum: {0} px..
        /// </summary>
        internal static string Error_ImageWidthGreaterThanMaximum {
            get {
                return ResourceManager.GetString("Error_ImageWidthGreaterThanMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon not specified..
        /// </summary>
        internal static string Error_InvalidIcon {
            get {
                return ResourceManager.GetString("Error_InvalidIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill category not specified..
        /// </summary>
        internal static string Error_InvalidSkillCategory {
            get {
                return ResourceManager.GetString("Error_InvalidSkillCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill description not specified..
        /// </summary>
        internal static string Error_InvalidSkillDescription {
            get {
                return ResourceManager.GetString("Error_InvalidSkillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill name not specified..
        /// </summary>
        internal static string Error_InvalidSkillName {
            get {
                return ResourceManager.GetString("Error_InvalidSkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill version not specified..
        /// </summary>
        internal static string Error_InvalidSkillVersion {
            get {
                return ResourceManager.GetString("Error_InvalidSkillVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Prism version created not specified..
        /// </summary>
        internal static string Error_InvalidVersionCreated {
            get {
                return ResourceManager.GetString("Error_InvalidVersionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Prism version tested not specified..
        /// </summary>
        internal static string Error_InvalidVersionTested {
            get {
                return ResourceManager.GetString("Error_InvalidVersionTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web API not specified in skill configuration..
        /// </summary>
        internal static string Error_InvalidWebApiId {
            get {
                return ResourceManager.GetString("Error_InvalidWebApiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value exceeds the maximum length (255) for this field: {0}.
        /// </summary>
        internal static string Error_MaxFieldLengthExceeded {
            get {
                return ResourceManager.GetString("Error_MaxFieldLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When creating a skill a provider must be specified..
        /// </summary>
        internal static string Error_ProviderMissingOnCreation {
            get {
                return ResourceManager.GetString("Error_ProviderMissingOnCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When updating a skill a provider cannot be specified..
        /// </summary>
        internal static string Error_ProviderSpecifiedOnUpdate {
            get {
                return ResourceManager.GetString("Error_ProviderSpecifiedOnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided release does not contain selected web api..
        /// </summary>
        internal static string Error_WebApiNotInRelease {
            get {
                return ResourceManager.GetString("Error_WebApiNotInRelease", resourceCulture);
            }
        }
    }
}
